// QuickJS subsystem: one `rquickjs::Runtime` plus the definition context.
// See: context/lib/scripting.md
//
// Lifecycle:
//   * One `rquickjs::Runtime` per subsystem (owns GC, memory limit).
//   * Two contexts per level:
//       - `definition_ctx`: long-lived context for cross-script definition-scope
//         code. Carries DefinitionOnly/Both primitives as real functions.
//       - Ephemeral data context: a short-lived context created fresh per level
//         in `run_data_script_quickjs`. This is the correct entry point for
//         level-load data-script execution — not `definition_ctx`.
//   * `__collect_definitions` is a magic sink injected into the definition
//     context only. It is NOT a registered primitive.

use std::cell::RefCell;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::rc::Rc;

use rquickjs::{CatchResultExt, CaughtError, Context, Ctx, FromJs, Function, IntoJs, Runtime};
use serde::{Deserialize, Serialize};

use super::error::ScriptError;
use super::primitives_registry::{PrimitiveRegistry, ScriptPrimitive};

/// Default memory cap per QuickJS `Runtime`. 100 MB is a comfortable ceiling
/// for the single-level working set; tune after profiling real content.
const DEFAULT_MEMORY_LIMIT: usize = 100 * 1024 * 1024;

/// Engine-internal name for the accumulator sink installed into the definition
/// context. Leading underscore is the convention the type-definition generator
/// uses to skip engine-internal functions.
const COLLECT_FN_NAME: &str = "__collect_definitions";

/// SDK library prelude bundled at compile time. Generated by `build.rs` from
/// `sdk/lib/**/*.ts` so the vocabulary symbols (`world`, `flicker`, `pulse`,
/// …) resolve as globals in every QuickJS context.
const SDK_PRELUDE_JS: &str = include_str!(concat!(env!("OUT_DIR"), "/prelude.js"));

/// Evaluate the SDK prelude inside `ctx`. The prelude is plain script-mode JS
/// — its `globalThis.x = expr` tail leaves the symbols available to scripts
/// loaded into the same context later.
pub fn evaluate_prelude(ctx: &Ctx<'_>) -> Result<(), ScriptError> {
    super::game_state_refs::install_quickjs_bridge(ctx)?;
    ctx.eval::<(), _>(SDK_PRELUDE_JS)
        .map_err(|e| ScriptError::ScriptThrew {
            msg: format!("failed to evaluate SDK prelude: {e}"),
            source_name: "sdk/lib/prelude.js".to_string(),
        })?;
    Ok(())
}

/// Configuration for a [`QuickJsSubsystem`]. `memory_limit_bytes` defaults to
/// 100 MB; override for measured workloads.
#[derive(Clone, Copy, Debug)]
pub struct QuickJsConfig {
    pub memory_limit_bytes: usize,
}

impl Default for QuickJsConfig {
    fn default() -> Self {
        Self {
            memory_limit_bytes: DEFAULT_MEMORY_LIMIT,
        }
    }
}

/// Placeholder archetype record. Sufficient to prove the Rust/JS round-trip
/// for definition-time accumulation; a future archetype plan replaces this
/// with the real descriptor shape.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArchetypeDescriptor {
    pub name: String,
}

/// Shared accumulator feeding `__collect_definitions`. Definition helpers push
/// into this `Vec`; the sink drains and returns it.
///
/// `Rc<RefCell<_>>` over `Arc<Mutex<_>>`: scripting is single-threaded (see
/// `scripting::ctx`) and `RefCell` does not poison.
pub type ArchetypeAccumulator = Rc<RefCell<Vec<ArchetypeDescriptor>>>;

/// rquickjs subsystem: one `Runtime`, one definition context, and the
/// primitive registry handle used by short-lived data contexts.
pub struct QuickJsSubsystem {
    runtime: Runtime,
    definition_ctx: Context,
    /// Kept so short-lived data contexts can reinstall primitives without
    /// requiring the caller to pass the registry back in. Each `ScriptPrimitive`
    /// is `Clone` with `Arc`-backed closures — cheap shallow copy.
    primitives: Vec<ScriptPrimitive>,
    /// Shared with the `__collect_definitions` function installed into
    /// `definition_ctx`.
    archetypes: ArchetypeAccumulator,
}

impl QuickJsSubsystem {
    /// Construct a subsystem: build the runtime, set the memory limit, and
    /// create the definition context with primitives installed.
    pub fn new(registry: &PrimitiveRegistry, cfg: &QuickJsConfig) -> Result<Self, ScriptError> {
        let runtime = Runtime::new().map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
        runtime.set_memory_limit(cfg.memory_limit_bytes);

        let archetypes: ArchetypeAccumulator = Rc::new(RefCell::new(Vec::new()));

        let primitives_snapshot: Vec<ScriptPrimitive> = registry.iter().cloned().collect();
        let definition_ctx =
            build_definition_context_from_snapshot(&runtime, &primitives_snapshot, &archetypes)?;

        Ok(Self {
            runtime,
            definition_ctx,
            primitives: primitives_snapshot,
            archetypes,
        })
    }

    /// Borrow the definition context so callers can enter it via `ctx.with`.
    pub fn definition_ctx(&self) -> &Context {
        &self.definition_ctx
    }

    /// Borrow the underlying `rquickjs::Runtime`.
    pub fn runtime(&self) -> &Runtime {
        &self.runtime
    }

    /// Borrow the primitive snapshot.
    pub fn primitives(&self) -> &[ScriptPrimitive] {
        &self.primitives
    }

    /// Shared handle to the archetype accumulator. Exposed for tests and for
    /// the caller that drains it after evaluating definition scripts.
    pub fn archetypes(&self) -> &ArchetypeAccumulator {
        &self.archetypes
    }
}

/// Evaluate `source` inside `ctx`, converting JS exceptions into
/// `ScriptError::ScriptThrew` and logging at `error` level. Must be called
/// inside a `ctx.with(...)` closure. A thrown exception does not poison the
/// context — subsequent calls continue to work.
pub fn run_script<'js, T>(ctx: &Ctx<'js>, source: &str, name: &str) -> Result<T, ScriptError>
where
    T: FromJs<'js>,
{
    match ctx.eval::<T, _>(source).catch(ctx) {
        Ok(v) => Ok(v),
        Err(caught) => Err(caught_error_to_script_error(caught, name)),
    }
}

/// Convert a `CaughtError` to `ScriptError::ScriptThrew` and log it.
/// Shared by `run_script` and future helpers that call into the context.
fn caught_error_to_script_error(caught: CaughtError<'_>, source: &str) -> ScriptError {
    let msg = caught.to_string();
    log::error!(target: "script/quickjs", "script `{source}` threw: {msg}");
    ScriptError::ScriptThrew {
        msg,
        source_name: source.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Context construction helpers.

fn build_definition_context_from_snapshot(
    runtime: &Runtime,
    primitives: &[ScriptPrimitive],
    archetypes: &ArchetypeAccumulator,
) -> Result<Context, ScriptError> {
    let ctx = Context::full(runtime).map_err(|e| ScriptError::InvalidArgument {
        reason: e.to_string(),
    })?;
    let archetypes = archetypes.clone();
    ctx.with(|ctx| -> Result<(), ScriptError> {
        install_primitives(&ctx, primitives)?;
        install_collect_definitions(&ctx, archetypes)?;
        evaluate_prelude(&ctx)?;
        Ok(())
    })?;
    Ok(ctx)
}

/// Install each primitive into `ctx`.
fn install_primitives(ctx: &Ctx<'_>, primitives: &[ScriptPrimitive]) -> Result<(), ScriptError> {
    for p in primitives {
        (p.quickjs_installer)(ctx).map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
    }
    Ok(())
}

/// Install the `__collect_definitions` sink as a global function on `ctx`.
/// Signature: `() -> ArchetypeDescriptor[]`. Drains the accumulator on each
/// call so a single definition pass cannot double-report.
fn install_collect_definitions(
    ctx: &Ctx<'_>,
    archetypes: ArchetypeAccumulator,
) -> Result<(), ScriptError> {
    let globals = ctx.globals();
    // `Vec<DescriptorJs>`: rquickjs' `IntoJs` for `Vec` encodes as a JS array;
    // the closure blanket impl handles `'js` lifetime threading without explicit
    // naming (not possible for closures in stable Rust).
    let f = Function::new(
        ctx.clone(),
        move |ctx: rquickjs::Ctx<'_>| -> rquickjs::Result<Vec<DescriptorJs>> {
            let result = catch_unwind(AssertUnwindSafe(|| {
                let drained: Vec<ArchetypeDescriptor> = archetypes.borrow_mut().drain(..).collect();
                drained
                    .into_iter()
                    .map(DescriptorJs::from)
                    .collect::<Vec<_>>()
            }));
            match result {
                Ok(v) => Ok(v),
                Err(_) => {
                    let err = ScriptError::Panicked {
                        name: COLLECT_FN_NAME,
                    };
                    Err(rquickjs::Exception::from_message(ctx.clone(), &err.to_string())?.throw())
                }
            }
        },
    )
    .map_err(|e| ScriptError::InvalidArgument {
        reason: e.to_string(),
    })?;
    globals
        .set(COLLECT_FN_NAME, f)
        .map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
    Ok(())
}

/// JS-facing shape for an `ArchetypeDescriptor`. Separate from the
/// serde-serializable record so the wire encoding stays decoupled from the
/// Rust-side representation.
struct DescriptorJs {
    name: String,
}

impl From<ArchetypeDescriptor> for DescriptorJs {
    fn from(d: ArchetypeDescriptor) -> Self {
        Self { name: d.name }
    }
}

impl<'js> IntoJs<'js> for DescriptorJs {
    fn into_js(self, ctx: &Ctx<'js>) -> rquickjs::Result<rquickjs::Value<'js>> {
        let o = rquickjs::Object::new(ctx.clone())?;
        o.set("name", self.name)?;
        Ok(o.into_value())
    }
}
