//! Committed byte-literal baselines for PRM serialization tests.
//!
//! These payloads deliberately exclude both the file header and per-slot
//! headers. They are source data, not output generated by `PrmFile::to_bytes`,
//! so a serialization-layout regression cannot update its own expectation.

pub const SINGLE_LAYER_DIFFUSE_PAYLOAD: [u8; 12] = [
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, // 2x1 level 0
    0x18, 0x19, 0x1A, 0x1B, // 1x1 level 1
];

pub const SINGLE_LAYER_SPECULAR_PAYLOAD: [u8; 3] = [
    0x20, 0x21, // 2x1 level 0
    0x22, // 1x1 level 1
];

pub const SINGLE_LAYER_NORMAL_PAYLOAD: [u8; 16] = [
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, // 4x4 BC5 level 0
    0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F,
];
