//! The two documents the SDK bundle generates: its quickstart README and the
//! `postretro.toml` that makes the bundle a project in its own right.
//!
//! See: context/lib/build_pipeline.md §Distribution packaging (§SDK bundle)

use crate::binaries::binary_name;
use crate::dist::payload::PAYLOAD_MOD_ROOT;
use crate::manifest::Manifest;

use super::{BIN_DIR, RELEASE_ENGINE_STEM};

/// Render the bundle's own project marker.
///
/// The bundle publishes the mod at `content/base` like a player payload does, so
/// its `mod_root` says so rather than repeating the source project's name. A
/// recipe source that pointed inside the old mod root is rewritten to follow;
/// one pointing outside it is left alone and reported, because the bundle ships
/// no tree it could have come from and a silently rewritten path would fail far
/// from its cause.
pub(super) fn render_bundle_manifest(manifest: &Manifest) -> String {
    let mut rendered = format!(
        "# Generated by `postretro-tool sdk-dist`. This bundle is a Postretro project:\n\
         # its presence is what lets `bin/postretro-tool dist` find the tree it is standing in.\n\
         [package]\n\
         name = \"{}\"\n\
         mod_root = \"{PAYLOAD_MOD_ROOT}\"\n",
        manifest.package.name
    );

    let source_prefix = format!("{}/", manifest.package.mod_root);
    for recipe in &manifest.recipes {
        rendered.push_str("\n[[recipes]]\n");
        rendered.push_str(&format!("output = \"{}\"\n", recipe.output));
        if let Some(source) = &recipe.source {
            let republished = match source.strip_prefix(&source_prefix) {
                Some(relative) => format!("{PAYLOAD_MOD_ROOT}/{relative}"),
                None => {
                    println!(
                        "  note: recipe `{}` sources {source}, which is outside the mod tree the \
                         bundle ships; its path is carried over unchanged",
                        recipe.output
                    );
                    source.clone()
                }
            };
            rendered.push_str(&format!("source = \"{republished}\"\n"));
        }
        if !recipe.args.is_empty() {
            let args = recipe
                .args
                .iter()
                .map(|argument| format!("\"{argument}\""))
                .collect::<Vec<_>>()
                .join(", ");
            rendered.push_str(&format!("args = [{args}]\n"));
        }
    }
    rendered
}

/// Render the modder quickstart README shipped at the bundle root.
pub(super) fn render_readme(package_name: &str, bundle_name: &str) -> String {
    let engine_binary = binary_name("postretro");
    let prl_build = binary_name("prl-build");
    let scripts_build = binary_name("scripts-build");
    let tool = binary_name("postretro-tool");
    let launcher = if cfg!(windows) {
        format!("{bundle_name}.bat")
    } else {
        format!("./{bundle_name}.sh")
    };
    format!(
        "# {package_name} — content-complete modding SDK\n\
\n\
This is a complete, content-complete kit for `{package_name}`. It is\n\
**playable out of the box** — the levels and material mips are already baked —\n\
and **fully editable** — it ships the mod's `.map`/`.ts` sources, the level and\n\
script compilers, the SDK definitions, the human-facing docs, the asset tools,\n\
and a debug/hot-reload authoring engine. Play it as-is, or edit and reload.\n\
\n\
The bundle is itself a Postretro project: `postretro.toml` at this root marks\n\
it, the mod lives at `{PAYLOAD_MOD_ROOT}/`, and `{BIN_DIR}/{tool}` builds a\n\
player distribution from it with no repository and no Rust toolchain.\n\
\n\
## Host-native caveat\n\
\n\
This bundle is **host-native**: the binaries were compiled for the operating\n\
system this bundle was built on and link native C/C++ dependencies. Run it on\n\
that same OS. To build for another platform, produce the bundle there.\n\
\n\
The engine at the bundle root is a **debug** build compiled with\n\
`--features dev-tools`: it auto-compiles `.ts` on load, hot-reloads script\n\
edits, and exposes the egui debug/inspector UI. It is not an optimized release\n\
build — `{BIN_DIR}/{}` is, and that is the engine a player\n\
distribution carries.\n\
\n\
## Flow A — play immediately\n\
\n\
Run `{launcher}`. It pins the working directory to this root and mounts\n\
`{PAYLOAD_MOD_ROOT}`, so the baked `maps/*.prl` levels and `baked/materials/`\n\
mips resolve with no build step.\n\
\n\
## Flow B — author (edit and reload)\n\
\n\
1. **Edit a level** in TrenchBroom using `sdk/TrenchBroom/postretro.fgd` and\n\
   `sdk/TrenchBroom/GameConfig.cfg`.\n\
2. **Recompile the level**:\n\
   `{BIN_DIR}/{prl_build} {PAYLOAD_MOD_ROOT}/maps/<name>.map --baked-root baked \\\n\
   --cache-dir .build-caches/prl-cache -o {PAYLOAD_MOD_ROOT}/maps/<name>.prl`.\n\
   `--baked-root` is what keeps the compiled `.prm` sidecars where the engine\n\
   reads them; omitting it degrades every world texture to a placeholder with a\n\
   warning rather than an error. `{BIN_DIR}/{tool} run` passes both for you.\n\
3. **Edit scripts** in TypeScript against `sdk/types/` and `sdk/lib/`. This debug\n\
   engine auto-compiles `.ts` on load and hot-reloads edits, so you can usually\n\
   skip a manual compile. To compile by hand:\n\
   `{BIN_DIR}/{scripts_build} --in {PAYLOAD_MOD_ROOT}/start-script.ts --out {PAYLOAD_MOD_ROOT}/start-script.js`.\n\
4. **Re-run**: `{BIN_DIR}/{tool} run`, or `{launcher}` again. The\n\
   `--features dev-tools` inspector is available in this build.\n\
\n\
## Flow C — build a player distribution\n\
\n\
From this directory:\n\
\n\
```\n\
{BIN_DIR}/{tool} dist\n\
```\n\
\n\
It bakes every level the mod's entry script names, assembles a payload under\n\
`dist/{package_name}/`, and writes a launcher beside the release engine. No\n\
cargo, no repository, no toolchain — the tool runs the binaries already in\n\
`{BIN_DIR}/`. See `docs/distribution.md`.\n\
\n\
## Further reading\n\
\n\
- `docs/level_design.md` — level authoring and the compiler pipeline.\n\
- `docs/scripting-reference.md` — the scripting API surface.\n\
- `docs/weapon-mounts.md` — weapon mount and viewmodel authoring.\n\
- `docs/diagnostics.md` — diagnosing and profiling a running session.\n\
- `tools/` — Python asset helpers. See `tools/README.md` for the Python and\n\
  library requirements they need.\n\
- `docs/distribution.md` — producing a lean, shippable **player** build.\n\
\n\
The engine binary name on this host is `{engine_binary}`.\n",
        binary_name(RELEASE_ENGINE_STEM)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundle_manifest_publishes_the_mod_at_the_payload_mod_root() {
        let manifest =
            Manifest::parse("[package]\nname = \"postretro-dev\"\nmod_root = \"content/dev\"\n")
                .expect("manifest parses");

        let rendered = render_bundle_manifest(&manifest);
        assert!(rendered.contains("name = \"postretro-dev\""), "{rendered}");
        assert!(
            rendered.contains(&format!("mod_root = \"{PAYLOAD_MOD_ROOT}\"")),
            "{rendered}"
        );
        // It must survive its own parser, or the bundle ships a project nothing
        // can open.
        Manifest::parse(&rendered).expect("the emitted bundle manifest parses");
    }

    #[test]
    fn bundle_manifest_repoints_recipe_sources_that_lived_inside_the_mod_tree() {
        let manifest = Manifest::parse(
            "[package]\nname = \"dev\"\nmod_root = \"content/dev\"\n\
             \n[[recipes]]\noutput = \"maps/arena.prl\"\n\
             source = \"content/dev/sources/arena.map\"\n\
             args = [\"--lightmap-density\", \"0.02\"]\n\
             \n[[recipes]]\noutput = \"maps/shared.prl\"\n\
             source = \"external/shared.map\"\n",
        )
        .expect("manifest parses");

        let rendered = render_bundle_manifest(&manifest);
        assert!(
            rendered.contains(&format!(
                "source = \"{PAYLOAD_MOD_ROOT}/sources/arena.map\""
            )),
            "{rendered}"
        );
        assert!(
            rendered.contains("source = \"external/shared.map\""),
            "a source outside the mod tree is carried over unchanged: {rendered}"
        );
        assert!(
            rendered.contains("args = [\"--lightmap-density\", \"0.02\"]"),
            "{rendered}"
        );

        let reparsed = Manifest::parse(&rendered).expect("the emitted bundle manifest parses");
        assert_eq!(reparsed.recipes.len(), 2);
        assert_eq!(reparsed.recipes[0].lightmap_density, Some(0.02));
    }

    #[test]
    fn readme_covers_all_three_flows_and_the_contract_points() {
        let readme = render_readme("postretro-dev", "postretro-dev-sdk");
        for needle in [
            "postretro-dev",
            "content-complete",
            "playable out of the box",
            "fully editable",
            "Flow A",
            "play immediately",
            "Flow B",
            "edit and reload",
            "Flow C",
            "player distribution",
            "host-native",
            "dev-tools",
            "hot-reload",
            "postretro.toml",
            "sdk/TrenchBroom/postretro.fgd",
            "GameConfig.cfg",
            "prl-build",
            "scripts-build",
            "postretro-tool",
            "--baked-root",
            "content/base/maps/<name>.prl",
            "docs/level_design.md",
            "docs/scripting-reference.md",
            "docs/weapon-mounts.md",
            "docs/diagnostics.md",
            "docs/distribution.md",
            "tools/",
        ] {
            assert!(readme.contains(needle), "README missing {needle:?}");
        }
    }

    /// The bundle's docs are read by someone with no cargo. An instruction they
    /// cannot follow is the defect this whole change closes.
    #[test]
    fn readme_never_tells_its_reader_to_run_cargo() {
        let readme = render_readme("postretro-dev", "postretro-dev-sdk");
        assert!(!readme.contains("cargo run"), "{readme}");
        assert!(!readme.contains("cargo build"), "{readme}");
    }
}
