// Generated by `gen-script-types`. Do not edit by hand.
declare module "postretro" {
  export type EntityId = number & { readonly __brand: "EntityId" };

  export type StateValue<T> = WritableStateRef<T>;

  export type Vec3 = { x: number; y: number; z: number };

  export type EulerDegrees = { pitch: number; yaw: number; roll: number };

  export type Transform = { position: Vec3; rotation: EulerDegrees; scale: Vec3 };

  /** Valid values: `transform`, `light`, `billboard_emitter`, `particle_state`, `sprite_visual`, `fog_volume`. */
  export type ComponentKind = "transform" | "light" | "billboard_emitter" | "particle_state" | "sprite_visual" | "fog_volume";

  export type ComponentValue = ({ kind: "transform" } & Transform) | ({ kind: "light" } & LightComponent) | ({ kind: "billboard_emitter" } & BillboardEmitterComponent) | ({ kind: "particle_state" } & ParticleState) | ({ kind: "sprite_visual" } & SpriteVisual) | ({ kind: "fog_volume" } & FogVolumeComponent);

  /** Authored dynamic-light preset attached to `EntityTypeDescriptor.components.light`. Field names are snake_case on the script surface. Descriptor-spawned lights are runtime-only and do not participate in baked indirect lighting. */
  export type LightDescriptor = {
    /** Linear RGB light color multiplier. Components are conventionally in [0, 1], though HDR values above 1 are accepted. */
    color: Vec3;
    /** Unitless brightness multiplier. Must be finite and ≥ 0; 0 produces no light. */
    intensity: number;
    /** Falloff range in metres. Must be finite and ≥ 0; 0 gives the light no spatial reach. */
    range: number;
    /** Authoring hint retained in the descriptor. Descriptor-spawned lights are currently always materialized as dynamic because they cannot contribute to baked lighting. */
    is_dynamic: boolean;
  };

  /** How a fade *into* an animation state takes over when another fade is already in flight. Absent in a descriptor defaults to `"smooth"`. Valid values: `smooth`, `snap`. */
  export type InterruptPolicy =
    /** Capture the in-flight blended pose once and blend the new fade from it — no discontinuity. */
    | "smooth"
    /** Blend the new fade from the interrupted state's clip; the in-flight blend drops — a deliberate, fade-window-bounded pop. */
    | "snap";

  /** One declared animation state: a named clip plus loop and crossfade policy. `clip` is resolved against the model's clip metadata at level load. */
  export type AnimationStateDescriptor = {
    /** Clip name this state plays. Must be non-empty; resolved against the model's clips at level load. */
    clip: string;
    /** Whether the clip loops. Optional; defaults to false. */
    loop?: boolean;
    /** Crossfade duration into this state, in milliseconds. Optional; must be finite and >= 0. Defaults to 150 ms. */
    crossfadeMs?: number;
    /** How a fade into this state takes over an in-flight fade. Optional; defaults to "smooth". */
    interrupt?: InterruptPolicy;
  };

  /** Authored mesh component preset attached to `EntityTypeDescriptor.components.mesh`. A descriptor carrying `components.mesh` is directly map-placeable via `canonicalName`. `model` is the skinned-model handle; `animations` declares the per-entity logical animation-state map (state name → clip + loop + crossfade + interrupt). When `animations` is present it must be non-empty and `defaultState` must name a declared state; omit both for a stateless mesh. */
  export type MeshDescriptor = {
    /** Skinned-model handle this entity renders. Must be non-empty. */
    model: string;
    /** Declared animation states keyed by author-defined state name (e.g. idle/locomotion/attack/death). Optional; when present, must be non-empty and accompanied by a `defaultState` naming one of these states. Omit for a stateless mesh. */
    animations?: { readonly [state: string]: AnimationStateDescriptor };
    /** The state entered at spawn. Required exactly when `animations` is present; must name a declared state. */
    defaultState?: string;
  };

  /** Entity archetype registered through `ModManifest.entities`. `defineEntity()` is a typed identity helper for constructing this object. The descriptor is engine-global and survives level unloads. */
  export type EntityTypeDescriptor = {
    /** Stable archetype name used by map classname routing and descriptor references. Required for direct map placement and for weapon descriptors referenced by `defaultWeapon`; omit only for archetypes that are never addressed by name. */
    canonicalName?: string;
    /** The `canonicalName` of a registered weapon archetype to instantiate and equip when this descriptor is selected by a `player_spawn` marker. Other spawn paths ignore this key. */
    defaultWeapon?: string;
    /** Optional component presets. Direct map placement materializes light, emitter, and movement presets; `player_spawn` does the same and may also equip `defaultWeapon`; weapon presets materialize on the separate wieldable entity created by that route. */
    components?: EntityTypeComponents;
  };

  /** Engine-managed billboard-particle emitter preset. Field names are snake_case on the script surface. Prefer the SDK `emitter()` builder or a preset such as `smokeEmitter()` when defaults are suitable. */
  export type BillboardEmitterComponent = {
    /** Continuous spawn rate in particles/sec. Must be finite and ≥ 0; 0 disables continuous spawning. */
    rate: number;
    /** Optional one-time particle count emitted when the component is materialized. null disables the burst. */
    burst: number | null;
    /** Random angular spread around `velocity`, in radians. Must be finite and ≥ 0; 0 emits in one direction. */
    spread: number;
    /** Lifetime of each particle in seconds. Must be finite and > 0. */
    lifetime: number;
    /** Initial particle velocity vector in metres/sec before random spread is applied. */
    velocity: Vec3;
    /** Unitless gravity multiplier using `verticalAcceleration = worldGravity * -buoyancy`: -1 falls at normal gravity, 0 floats, values between -1 and 0 sink more slowly, and positive values rise. */
    buoyancy: number;
    /** Velocity damping coefficient in 1/sec. Must be finite and ≥ 0; 0 preserves velocity apart from buoyancy. */
    drag: number;
    /** Non-empty normalized-lifetime curve of billboard size multipliers. Samples are evenly spaced from spawn to death. */
    size_over_lifetime: ReadonlyArray<number>;
    /** Non-empty normalized-lifetime curve of opacity multipliers. Samples are evenly spaced from spawn to death. */
    opacity_over_lifetime: ReadonlyArray<number>;
    /** RGB multiplier applied to every emitted particle. Components are conventionally in [0, 1], with values above 1 available for HDR tinting. */
    color: Vec3;
    /** Non-empty sprite/material identifier resolved by the billboard renderer. */
    sprite: string;
    /** Initial billboard angular velocity in radians/sec. Positive and negative values rotate in opposite directions. */
    spin_rate: number;
    /** Optional spin-rate tween. null keeps `spin_rate` constant. */
    spin_animation: SpinAnimation | null;
  };

  /** Spin-rate tween carried by a billboard emitter and consumed by `setSpinRate`. */
  export type SpinAnimation = {
    /** Tween duration in seconds. Must be finite and > 0. */
    duration: number;
    /** Non-empty curve of spin rates in radians/sec, sampled evenly across `duration`. */
    rate_curve: ReadonlyArray<number>;
  };

  /** Animation curves attached to a fog volume by the `setFogAnimation` reaction primitive. Four independent channels share `periodMs` / `phase` / `playCount`: `density` modulates volumetric density, `saturation` modulates SH-irradiance saturation, `minBrightness` modulates the scatter brightness floor, and `lightRange` scales how far lights reach inside the fog. At least one curve must be present when `playCount` is finite — otherwise the animation has nothing to settle to. `phase` is normalized into `[0, 1)`. `playCount = null` loops forever; finite counts have the bridge write back each channel's final keyframe as static state on completion. There is no `startActive` flag — fog has no GPU descriptor for the curve, so absence (`null`) is the only inactive state. */
  export type FogAnimation = {
    /** Total period of the loop, in milliseconds. */
    periodMs: number;
    /** Starting phase in [0.0, 1.0). Values outside this range are normalized via rem_euclid. */
    phase: number | null;
    /** Total full periods to play; null loops forever. */
    playCount: number | null;
    /** Per-sample density curve. null leaves the static density unchanged. */
    density: ReadonlyArray<number> | null;
    /** Per-sample saturation curve. null leaves the static saturation unchanged. */
    saturation: ReadonlyArray<number> | null;
    /** Per-sample animation curve for the `min_brightness` channel (scatter brightness floor). null leaves the static min_brightness unchanged. Each sample clamped to `[0, +∞)`; empty curve is rejected. */
    minBrightness: ReadonlyArray<number> | null;
    /** Per-sample animation curve for the `light_range` channel (scales how far lights reach inside this fog). null leaves the static light_range unchanged. Each sample must be strictly positive and finite; non-positive or non-finite samples clamp to `0.001`; empty curve is rejected. */
    lightRange: ReadonlyArray<number> | null;
  };

  /** Script-facing fog-volume component shape. Carried by `FogVolume` ECS entities; the AABB is baked at level load and lives in the FogVolumeBridge side-table — it is not exposed here because it is not runtime-settable. */
  export type FogVolumeComponent = {
    /** Volumetric fog density inside the AABB. */
    density: number;
    /** How much the fog lights up near light sources. 0 = stays dark even under bright lights, 1 = picks up full light color. Raise for misty glow, lower for thick opaque smoke. */
    glow: number;
    /** Edge softness in world units: 0 = hard cutoff at the brush face, larger = wider linear ramp inward from each face. */
    edgeSoftness: number;
    /** Radial falloff exponent. Consulted by the radial (`fog_lamp`, `fog_tube`) and ellipsoid (axis-aligned `fog_volume`) shader paths; stored but ignored by the plane-sweep (non-axis-aligned `fog_volume`) path. */
    falloff: number;
    /** Per-volume RGB scatter multiplier. Default `[1.0, 1.0, 1.0]`. */
    tint: readonly [number, number, number];
    /** Saturation of transmitted SH irradiance: 0 = greyscale, 1 = natural, >1 = boosted. Default 1.0. */
    saturation: number;
    /** Floor on per-volume scatter brightness. Clamped to `[0, +∞)`. Default 0.0. */
    minBrightness: number;
    /** Scales how far lights reach inside this fog. 1.0 = same range as open air, 2.0 = double range, 0.5 = half range. Strictly positive; clamps to 0.001. Default 1.0. */
    lightRange: number;
    /** Optional animation carrying any combination of density, saturation, minBrightness, and lightRange curves. null holds the static state. */
    animation: FogAnimation | null;
  };

  /** Entity handle returned by `world.query` when filtering for fog-volume entities. */
  export type FogVolumeEntity = {
    id: EntityId;
    /** Volume center at query time (AABB midpoint, baked at level load). */
    position: Vec3;
    /** The entity's tags at query time. Empty array if untagged. */
    tags: ReadonlyArray<string>;
    /** Full fog-volume component snapshot at query time. */
    component: FogVolumeComponent;
  };

  /** Component presets carried by `EntityTypeDescriptor.components`. Each key is optional and independent; present values are validated when the mod manifest loads. */
  export type EntityTypeComponents = {
    /** Dynamic-light preset materialized on each spawned instance. */
    light?: LightDescriptor | null;
    /** Billboard-particle emitter preset materialized on each spawned instance. */
    emitter?: BillboardEmitterComponent | null;
    /** Player movement, collision capsule, and first-person view-feel preset. */
    movement?: PlayerMovementDescriptor | null;
    /** Weapon tuning preset. Weapon archetypes are instantiated as wieldable entities when referenced by `defaultWeapon`. */
    weapon?: WeaponDescriptor | null;
    /** Animated skinned-mesh preset: model handle plus an optional per-state animation map. A descriptor carrying this is directly map-placeable by canonicalName. */
    mesh?: MeshDescriptor | null;
    /** Hit points plus an optional hitscan hitbox. A descriptor carrying this is directly map-placeable by canonicalName. */
    health?: HealthDescriptor | null;
    /** AI brain preset: detection/attack/leash ranges, attack tuning, move speed, despawn delay, and the logical-state → mesh animation-state map. Materializes a brain plus a navigation agent at spawn. Rides on health+mesh for map placement; it does not itself make a descriptor placeable. */
    ai?: AiDescriptor | null;
  };

  /** Valid values: `semi`, `auto`. */
  export type FireMode =
    /** One shot per press. */
    | "semi"
    /** Continuous fire while held. */
    | "auto";

  /** Valid values: `hitscan`. */
  export type ResolutionMode =
    /** Resolve instantly against the static-world collision ray. */
    | "hitscan";

  /** Authored weapon component preset. Descriptor-owned tuning data; maps do not override these params. Spawn-time player equip materializes a separate wieldable instance entity from this descriptor. */
  export type WeaponDescriptor = {
    /** Base damage payload per resolved shot. Must be finite and ≥ 0. */
    damage: number;
    /** Maximum hitscan distance in metres. Must be finite and > 0. */
    range: number;
    /** Minimum interval between shots in milliseconds. Must be finite and > 0. */
    fireRateMs: number;
    /** Semi or automatic input gate. */
    fireMode: FireMode;
    /** Shot resolution mode. Currently supports hitscan only. */
    resolution: ResolutionMode;
  };

  /** One world-aligned AABB hitbox. Carrying one makes the entity hitscan-targetable. `halfExtents` is the box half-size on each axis; `offset` shifts the box center from the entity's transform position. */
  export type HitboxDescriptor = {
    /** Box half-size on each axis, in metres. Each element must be finite and > 0. */
    halfExtents: readonly [number, number, number];
    /** Center offset from the entity's transform position, in metres. Each element must be finite. Optional; defaults to [0, 0, 0]. */
    offset?: readonly [number, number, number];
  };

  /** Authored health component preset attached to `EntityTypeDescriptor.components.health`. `max` is the entity's hit-point ceiling; the optional `hitbox` makes the entity hitscan-targetable (one world-aligned AABB, fixed per archetype). Materializes into a Health component with `current == max` at spawn. */
  export type HealthDescriptor = {
    /** Maximum hit points. Must be finite and >= 1.0; `current` initializes to this value at spawn. */
    max: number;
    /** Optional hitscan hitbox. Present ⇒ the entity can be ray-targeted by weapons; absent ⇒ it cannot. */
    hitbox?: HitboxDescriptor;
    /** Per-skeletal-zone damage multipliers, tag → factor (e.g. `{ head: 1.5 }`). A shot on a tagged zone scales the weapon's payload by this factor; an absent zone or unlisted tag applies 1.0. Each factor must be finite and >= 0. Optional; defaults to empty. */
    zoneMultipliers?: { readonly [tag: string]: number };
  };

  /** The closed logical-state → animation-state name mapping carried by `AiDescriptor.states`. Each value names a state declared in the entity's `components.mesh.animations`; the brain switches the mesh to the matching state when it enters that logical state. All four keys are required and the set is closed (no other keys allowed). */
  export type AiStateNames = {
    /** Mesh state played while the brain is idle (no target). Must name a declared mesh animation state. */
    idle: string;
    /** Mesh state played while the brain is alerted and pursuing a target (the chase/locomotion state). Must name a declared mesh animation state. */
    alert: string;
    /** Mesh state played while the brain attacks. Must name a declared mesh animation state. */
    attack: string;
    /** Mesh state played when the brain dies. Must name a declared mesh animation state. */
    death: string;
  };

  /** Authored AI brain component preset attached to `EntityTypeDescriptor.components.ai`. Descriptor-owned tuning: maps never override these. Materializes the engine-owned brain (logical state + timers) and a movable navigation agent at spawn. Distances are in metres, times in milliseconds, `moveSpeed` in metres/sec. The `states` block links the brain's logical states to mesh animation states; that cross-component mapping is validated at spawn (the ai block cannot see the mesh block at its own parse). */
  export type AiDescriptor = {
    /** Distance at which the brain notices a target and leaves idle, in metres. Must be finite and > 0. */
    detectionRange: number;
    /** Distance within which the brain attacks rather than pursues, in metres. Must be finite and > 0. */
    attackRange: number;
    /** Distance from its origin past which the brain disengages and returns, in metres. Must be finite and > 0. */
    leashRange: number;
    /** Damage dealt per attack. Must be finite and >= 0 (a negative value would heal the target through the damage chokepoint). */
    attackDamage: number;
    /** Minimum interval between attacks, in milliseconds. Must be finite and > 0. */
    attackCooldownMs: number;
    /** Pursuit movement speed in metres/sec, seeding the navigation agent. Must be finite and > 0. */
    moveSpeed: number;
    /** Delay between death and despawn, in milliseconds (lets the death animation play out). Must be finite and > 0. */
    deathDespawnMs: number;
    /** Closed logical-state → mesh animation-state name mapping (idle / alert / attack / death). Each value must name a state declared in `components.mesh.animations`; validated at spawn. */
    states: AiStateNames;
  };

  /** Authored player-movement preset. `capsule`, `ground`, `air`, and `fall` are required. `dash`, `crouch`, and `viewFeel` are opt-in features; `forgiveness` has engine defaults when omitted. Distances use metres and time uses seconds unless a key is suffixed `Ms`. */
  export type PlayerMovementDescriptor = {
    /** Required collision capsule and camera attachment geometry, in metres. */
    capsule: CapsuleParams;
    /** Required on-ground speed, acceleration, stepping, and slope limits. */
    ground: GroundParams;
    /** Required jump and mid-air steering parameters. */
    air: AirParams;
    /** Required terminal falling-speed limit. */
    fall: FallParams;
    /** Optional dash tuning. When omitted, dash is disabled. When present, all of its fields are required. */
    dash?: DashParams;
    /** Optional input-forgiveness tuning (coyote time + jump buffer). When the whole object is omitted, the documented engine defaults apply (~100ms each). When present, each field is itself optional and falls back to its engine default; 0 disables that grace. */
    forgiveness?: ForgivenessParams;
    /** Optional crouch tuning. When omitted, crouch is disabled. When present, all of its fields are required. */
    crouch?: CrouchParams;
    /** Optional first-person view-feel tuning (head bob, strafe tilt, ambient sway). A render-only camera effect. When omitted, view feel is disabled. When present, each of `bob`/`tilt`/`sway` is independently optional. */
    viewFeel?: ViewFeelParams;
    /** Optional. Stuck-stop deadzone enable flag. When true (default), the slide loop zeroes horizontal velocity and rolls back XZ position when contradictory wall normals (≥60° apart) are seen within the same tick AND net horizontal displacement is below `stuckStopThreshold`. Suppresses orbital jitter in interior corners. Default true. */
    stuckStopEnabled?: boolean;
    /** Optional. Horizontal-displacement threshold in metres that gates the deadzone. Must be finite and ≥ 0. Default 1.0e-3. */
    stuckStopThreshold?: number;
  };

  /** Player collision capsule. `halfHeight` is the cylinder half-height; total capsule height is `2 * (halfHeight + radius)`. `eyeHeight` is the camera attachment point measured upward from the capsule center. */
  export type CapsuleParams = {
    /** Capsule radius in metres. Must be finite and > 0. */
    radius: number;
    /** Cylinder half-height in metres, excluding the rounded caps. Must be finite and > 0. */
    halfHeight: number;
    /** Camera attachment point measured upward from the capsule center in metres. Must be finite and lie in (0, halfHeight + radius]. */
    eyeHeight: number;
  };

  /** On-ground locomotion parameters. `maxSlope` is in degrees on the wire and converted to a cosine at materialization. */
  export type GroundParams = {
    /** Horizontal walk, run, and crouch target speeds in metres/sec. */
    speed: SpeedParams;
    /** Ground acceleration in metres/sec². Must be finite and ≥ 0. */
    accel: number;
    /** Maximum automatic step-up height in metres. Must be finite and ≥ 0; 0 disables stepping. */
    stepHeight: number;
    /** Steepest walkable surface angle in degrees. Must be finite and lie in [0, 90]. */
    maxSlope: number;
  };

  /** Walk, run, and crouch ground speeds in metres/sec. The movement tick uses `run` while sprint is held, `crouch` while crouched, and `walk` otherwise, applied omnidirectionally. All required and must be finite and ≥ 0. */
  export type SpeedParams = {
    /** Steady-state horizontal speed in metres/sec when not sprinting. Must be finite and ≥ 0. */
    walk: number;
    /** Steady-state horizontal speed in metres/sec while sprint is held. Must be finite and ≥ 0. */
    run: number;
    /** Steady-state horizontal speed in metres/sec while crouched. Must be finite and ≥ 0. */
    crouch: number;
  };

  /** Mid-air control parameters. `forwardSteer` blends forward steering authority between 0 (pure strafe-only Quake air control) and 1 (full forward authority). `jumpCeiling` is required when `jumps > 0`. */
  export type AirParams = {
    /** Forward steering authority in [0, 1]. */
    forwardSteer: number;
    /** Air acceleration in metres/sec². Must be finite and ≥ 0. */
    accel: number;
    /** Horizontal speed cap in metres/sec that air acceleration can push toward. Must be finite and ≥ 0. */
    maxControlSpeed: number;
    /** Permit chained jumps on landing without releasing the jump input. */
    bunnyHop: boolean;
    /** Additional jumps allowed in air after the initial ground jump. 0 disables air jumps. */
    jumps: number;
    /** Upward velocity in metres/sec applied by a ground jump. Must be finite and ≥ 0. */
    jumpVelocity: number;
    /** Air-jump activation threshold in metres/sec: an air jump may fire only while current vertical velocity is ≤ this value, after which velocity is set to `jumpVelocity`. Required when `jumps > 0`; 0 is conventional when air jumps are disabled. */
    jumpCeiling: number;
  };

  /** Falling parameters. */
  export type FallParams = {
    /** Maximum downward fall speed magnitude in metres/sec. Must be finite and > 0. */
    terminalVelocity: number;
  };

  /** Dash tuning. Optional on `PlayerMovementDescriptor` — when omitted, dash is disabled. When present, all fields are required and validated. */
  export type DashParams = {
    /** Impulse magnitude applied on dash in metres/sec. A literal must be finite > 0. Accepts a runtime expression, evaluated at dash entry. */
    boostSpeed: number | RuntimeValue;
    /** Fraction of pre-dash momentum folded into the dash, unitless in [0, 1]. Accepts a runtime expression, evaluated at dash entry. */
    momentumRetention: number | RuntimeValue;
    /** In-dash steering authority, unitless in [0, 1]. Accepts a runtime expression, evaluated per tick during the dash. */
    steerControl: number | RuntimeValue;
    /** Decay rate of the dash impulse in metres/sec². A literal must be finite and ≥ 0. Accepts a runtime expression, evaluated per tick during the dash. */
    dashDrag: number | RuntimeValue;
    /** Cooldown between dashes in milliseconds. A literal must be finite and ≥ 0. Accepts a runtime expression, evaluated at dash entry. */
    cooldownMs: number | RuntimeValue;
    /** Number of air dashes allowed before landing. */
    airDashes: number;
    /** Whether the dash preserves the pre-dash vertical velocity. Accepts a runtime expression, evaluated at dash entry. */
    preserveVertical: boolean | RuntimeValue;
  };

  /** Crouch tuning. Optional on `PlayerMovementDescriptor` — when omitted, crouch is disabled. When present, all fields are required and validated. */
  export type CrouchParams = {
    /** Crouched capsule half-height in metres. Must be finite > 0. */
    halfHeight: number;
    /** Crouched camera attachment point measured upward from the capsule center in metres. Must lie in (0, crouched halfHeight + radius]. */
    eyeHeight: number;
    /** Rate the capsule interpolates between standing and crouched extents, per-sec. Must be finite > 0. */
    transitionRate: number;
  };

  /** First-person view-feel tuning: a render-only camera effect bundle (head bob, strafe tilt, ambient sway). Optional on `PlayerMovementDescriptor` — when omitted, view feel is disabled. When present, each of `bob`/`tilt`/`sway` is independently optional; an absent sub-object disables that motion. */
  export type ViewFeelParams = {
    /** Optional head-bob tuning. When omitted, head bob is disabled. When present, all of its fields are required except `groundedOnly`. */
    bob?: BobParams;
    /** Optional strafe-tilt tuning. When omitted, strafe tilt is disabled. When present, all of its fields are required except `groundedOnly`. */
    tilt?: TiltParams;
    /** Optional ambient-sway tuning. When omitted, ambient sway is disabled. When present, all of its fields are required except `groundedOnly`. */
    sway?: SwayParams;
  };

  /** Distance-phased head-bob tuning. Vertical and lateral motion have independent cadences. All fields are required except `groundedOnly`, which defaults to true. */
  export type BobParams = {
    /** Vertical oscillation cycles per metre travelled. Must be finite and > 0; larger values produce quicker up/down steps. */
    verticalFrequency: number;
    /** Lateral oscillation cycles per metre travelled. Must be finite and > 0. Half of `verticalFrequency` produces the classic one side-to-side cycle per two vertical cycles. */
    lateralFrequency: number;
    /** Peak vertical eye displacement in metres. Must be finite and ≥ 0; 0 disables vertical displacement. */
    verticalAmplitude: number;
    /** Peak side-to-side eye displacement in metres. Must be finite and ≥ 0; 0 disables lateral displacement. */
    lateralAmplitude: number;
    /** Horizontal speed in metres/sec at or below which bob outputs zero and holds both phases. Must be finite and ≥ 0; amplitude eases in over the next 1 m/s. */
    speedThreshold: number;
    /** When true, airborne bob outputs zero and holds both phases. Optional; defaults to true. */
    groundedOnly?: boolean;
  };

  /** Strafe-tilt tuning. When present on `viewFeel`, all fields are required and validated except `groundedOnly`, which is optional and defaults to true. */
  export type TiltParams = {
    /** Maximum tilt angle in degrees. Must be finite in [0, 90]. */
    maxAngle: number;
    /** Lateral speed in metres/sec at which tilt reaches `maxAngle`. Must be finite and > 0. */
    speedReference: number;
    /** Spring natural-frequency tuning in 1/sec. Must be finite and > 0; larger values track direction changes more quickly. */
    tension: number;
    /** Whether tilt applies only while grounded. Optional; defaults to true. */
    groundedOnly?: boolean;
  };

  /** Ambient-sway tuning. When present on `viewFeel`, all fields are required and validated except `groundedOnly`, which is optional and defaults to false. */
  export type SwayParams = {
    /** Sway amplitude in degrees. Must be finite and ≥ 0. */
    amplitude: number;
    /** Sway oscillation frequency in Hz. Must be finite > 0. */
    frequency: number;
    /** Additional sway multiplier per metre/sec of horizontal speed. Must be finite and ≥ 0; 0 makes sway independent of movement speed. */
    speedScale: number;
    /** Whether sway applies only while grounded. Optional; defaults to false. */
    groundedOnly?: boolean;
  };

  /** Input-forgiveness tuning (coyote time + jump buffering). Optional on `PlayerMovementDescriptor` — when the whole `forgiveness` object is omitted, the documented engine defaults apply. When present, each field is itself optional and falls back to its engine default; an explicit 0 disables that grace independently. Both windows are in milliseconds. */
  export type ForgivenessParams = {
    /** Coyote-time window in milliseconds: a grounded jump is permitted for this long after leaving a ledge (with no prior jump). 0 disables coyote time. Default 100.0. */
    coyoteMs?: number;
    /** Jump-buffer window in milliseconds: a jump pressed this long before landing fires on the landing tick. 0 disables jump buffering. Default 100.0. */
    jumpBufferMs?: number;
  };

  /** A UI tree registered through `ModManifest.uiTrees` (or `LevelManifest.uiTrees`). Pairs a registry `name` with an `AnchoredTree` placement envelope and the `alwaysOn` registration flag. A malformed entry is logged and skipped at load time. */
  export type ModUiTree = {
    /** Registry name the render path resolves the tree by. Required. */
    name: string;
    /** The placement envelope + widget tree (the value produced by the `Tree` factory). Required. */
    tree: AnchoredTreeDescriptor;
    /** Whether the tree composes as a per-frame base layer (e.g. the HUD: always rendered) rather than only when explicitly pushed onto the modal stack. Optional; defaults to false. */
    alwaysOn?: boolean;
  };

  /** One map listed in `ModManifest.maps`. Use `defineMapCatalog([...])` for a typed construction site; the returned array keeps this exact wire shape. The catalog is committed during mod init and is available before any level loads. */
  export type ModMapEntry = {
    /** Stable logical map handle used by `loadLevel(id)`, frontend `backgroundLevel`, and future references. Required; exact string match. */
    id: string;
    /** PRL path authored relative to the content root, such as `base/maps/e1m1.prl`. Required. */
    path: string;
    /** Display name shown to players in catalog-driven UI. Required. */
    name: string;
    /** Authoritative classification tags for filtering plus `levels` selection on mod-global reactions and crossings. Optional; missing/null normalizes to empty. */
    tags?: ReadonlyArray<string>;
  };

  /** Static camera pose used while a mod frontend menu is presented. All fields are required when `ModManifest.frontend` is present. */
  export type MenuCamera = {
    /** World-space camera position in metres as `[x, y, z]`. Required. */
    position: readonly [number, number, number];
    /** Camera yaw in radians. Required. */
    yaw: number;
    /** Camera pitch in radians. Required. */
    pitch: number;
  };

  /** Mod frontend declaration. Selects the startup menu tree, optional background catalog map, and static menu camera pose. Omit `frontend` to use the engine fallback menu. */
  export type Frontend = {
    /** UI tree registry name presented as the frontend menu. Required; if the name is not registered, the engine fallback frontend is shown. */
    menuTree: string;
    /** Map catalog id to load behind the frontend menu. Optional; omit for no backdrop level. */
    backgroundLevel?: string;
    /** Static menu camera pose. Required. */
    camera: MenuCamera;
  };

  /** Theme token maps supplied via `ModManifest.theme`. Three category-scoped maps: colors (linear-RGBA), fonts (registered family name), spacing (logical px). Each is optional; overrides merge per-token into the engine default. */
  export type ThemeTokens = {
    /** Color tokens: token name → linear-RGBA `[r, g, b, a]`. Optional. */
    colors?: { readonly [token: string]: readonly [number, number, number, number] };
    /** Font tokens: token name → registered family name. Optional. */
    fonts?: { readonly [token: string]: string };
    /** Spacing tokens: token name → logical px. Optional. */
    spacing?: { readonly [token: string]: number };
  };

  /** Mod manifest consumed from `start-script.ts`'s default export or `start-script.luau`'s chunk return. `defineMod(config)` is a pure typed identity helper for this object; the engine commits its data only after manifest validation succeeds. */
  export type ModManifest = {
    /** Human-readable mod name used for diagnostics and UI. Required. */
    name: string;
    /** Engine-global entity-type registrations. Optional; survive level unload and are committed only after the manifest validates. */
    entities?: ReadonlyArray<EntityTypeDescriptor>;
    /** Script-registered UI trees (name + `AnchoredTree` + `alwaysOn`). Optional; malformed entries are logged and skipped without aborting boot. */
    uiTrees?: ReadonlyArray<ModUiTree>;
    /** Theme token overrides (colors/fonts/spacing). Optional; merged per-token into the engine default. */
    theme?: ThemeTokens;
    /** Font assets: family name → TTF asset path. Optional; changing custom font assets requires an engine restart. */
    fonts?: { readonly [token: string]: string };
    /** Pre-load-discoverable map catalog. Optional; use catalog ids with `loadLevel(id)` and `frontend.backgroundLevel`. */
    maps?: ReadonlyArray<ModMapEntry>;
    /** Mod-defined frontend menu declaration. Optional; omission clears the mod frontend and presents the engine fallback menu. */
    frontend?: Frontend;
    /** Engine-global reaction definitions. Optional; survive level unload and compose into active level behavior by `levels` tag selectors. */
    reactions?: ReadonlyArray<NamedReactionDescriptor>;
    /** Engine-global state-crossing watchers. Optional; survive level unload and compose into active level behavior by `levels` tag selectors. */
    crossings?: ReadonlyArray<CrossingDescriptor>;
    /** Engine-global state-store declarations returned by `defineStore(...).declaration`. Optional; commit atomically after the manifest validates and preserve existing values when the schema is identical. */
    stores?: ReadonlyArray<StoreDeclaration>;
  };

  /** Returns true if the entity id refers to a live entity. */
  export function entityExists(id: EntityId): boolean;
}
