// Generated by `gen-script-types`. Do not edit by hand.
declare module "postretro" {
  export type EntityId = number & { readonly __brand: "EntityId" };

  /** A widget the modder configures. */
  export type Widget = {
    /** Unique widget id. */
    id: EntityId;
    count: number;
  };

  /** Valid values: `Alpha`, `Beta`. */
  export type Kind =
    /** The first kind. */
    | "Alpha"
    | "Beta";

  export type Payload =
    /** Numeric payload. */
    | { kind: "Alpha"; value: number }
    /** Textual payload. */
    | { kind: "Beta"; value: string };

  export type Action =
    /** Move the entity by a vector. */
    | { type: "Move"; data: Vec3 }
    | { type: "Stop"; data: number };

  export type Event = {
    name: string;
    /** Opaque event data — payload shape is script-defined. */
    data: unknown;
  };
}
