// Luau SDK type-definition emission.
// See: context/lib/scripting.md §7

use std::fmt::Write as _;

use super::common::{
    luau_field_parts, remove_decl_line, remove_doc_and_decl_line, remove_range, rust_to_luau,
    string_enum_doc,
};
use crate::engine_state_catalog::{
    EngineStateCapability, EngineStateTreeNode, EngineStateValueType, engine_state_catalog,
};
use crate::primitives_registry::{RegisteredType, TaggedVariant, TypeShape};

pub(super) const LUAU_HEADER: &str = "-- Generated by `gen-script-types`. Do not edit by hand.\n";

/// Indent used for fields/variants inside a multi-line Luau type body.
const LUAU_FIELD_INDENT: &str = "  ";

fn luau_doc_line(doc: &str, indent: &str, out: &mut String) {
    if doc.is_empty() {
        return;
    }
    writeln!(out, "{indent}--- {doc}").unwrap();
}

pub(super) fn emit_luau_type(ty: &RegisteredType, out: &mut String) {
    if !matches!(&ty.shape, TypeShape::StringEnum { .. }) {
        luau_doc_line(ty.doc, "", out);
    }
    match &ty.shape {
        TypeShape::Brand { underlying } => {
            writeln!(out, "export type {} = {underlying}", ty.name).unwrap();
        }
        TypeShape::GenericBrand {
            type_param,
            underlying,
        } => {
            if ty.name == "StateValue" {
                writeln!(
                    out,
                    "export type StateValue<{type_param}> = WritableStateRef<{type_param}>",
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "export type {name}<{type_param}> = {underlying} & {{ __brand: \"{name}\" }}",
                    name = ty.name,
                )
                .unwrap();
            }
        }
        TypeShape::Struct { fields } => {
            let any_doc = fields.iter().any(|f| !f.doc.is_empty());
            if !any_doc {
                let body = fields
                    .iter()
                    .map(|f| {
                        let (name, ty) = luau_field_parts(f.name, f.ty_name);
                        format!("{name}: {ty}")
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(out, "export type {} = {{ {body} }}", ty.name).unwrap();
            } else {
                writeln!(out, "export type {} = {{", ty.name).unwrap();
                for f in fields {
                    luau_doc_line(f.doc, LUAU_FIELD_INDENT, out);
                    let (name, ty_str) = luau_field_parts(f.name, f.ty_name);
                    writeln!(out, "{LUAU_FIELD_INDENT}{name}: {ty_str},").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
        TypeShape::StringEnum { variants } => {
            let doc = string_enum_doc(ty.doc, variants);
            luau_doc_line(&doc, "", out);
            let any_doc = variants.iter().any(|v| !v.doc.is_empty());
            if !any_doc {
                let body = variants
                    .iter()
                    .map(|v| format!("\"{}\"", v.name))
                    .collect::<Vec<_>>()
                    .join(" | ");
                writeln!(out, "export type {} = {body}", ty.name).unwrap();
            } else {
                writeln!(out, "export type {} =", ty.name).unwrap();
                for (i, v) in variants.iter().enumerate() {
                    luau_doc_line(v.doc, LUAU_FIELD_INDENT, out);
                    let prefix = if i == 0 { "" } else { "| " };
                    writeln!(out, "{LUAU_FIELD_INDENT}{prefix}\"{}\"", v.name).unwrap();
                }
            }
        }
        TypeShape::TaggedUnion {
            tag_field,
            value_field,
            flat,
            variants,
        } => {
            let render_variant = |v: &TaggedVariant| -> String {
                if *flat {
                    // Luau lacks a TS-style intersection operator, so a flat
                    // ComponentValue variant is spelled as the payload type
                    // intersected with the tag literal via a type alias. We
                    // approximate it as `Payload & { kind: "x" }` using the
                    // typeof / intersection workaround — luau-lsp accepts
                    // `T & { tag: "kind" }`. (Equivalent to the TS form.)
                    format!(
                        "({} & {{ {tag_field}: \"{}\" }})",
                        rust_to_luau(v.value_ty),
                        v.kind
                    )
                } else {
                    format!(
                        "{{ {tag_field}: \"{}\", {value_field}: {} }}",
                        v.kind,
                        rust_to_luau(v.value_ty)
                    )
                }
            };
            let any_doc = variants.iter().any(|v| !v.doc.is_empty());
            if !any_doc {
                let body = variants
                    .iter()
                    .map(&render_variant)
                    .collect::<Vec<_>>()
                    .join(" | ");
                writeln!(out, "export type {} = {body}", ty.name).unwrap();
            } else {
                writeln!(out, "export type {} =", ty.name).unwrap();
                for (i, v) in variants.iter().enumerate() {
                    luau_doc_line(v.doc, LUAU_FIELD_INDENT, out);
                    let prefix = if i == 0 { "" } else { "| " };
                    writeln!(out, "{LUAU_FIELD_INDENT}{prefix}{}", render_variant(v)).unwrap();
                }
            }
        }
    }
}

pub fn state_ref_luau(
    capability: EngineStateCapability,
    value_type: EngineStateValueType<'_>,
) -> String {
    let ref_ty = if capability == EngineStateCapability::Writable {
        "WritableStateRef"
    } else {
        "ReadonlyStateRef"
    };
    format!("{ref_ty}<{}>", value_type.to_luau())
}

fn emit_luau_game_state_node(
    node: &EngineStateTreeNode,
    catalog: &[crate::engine_state_catalog::EngineStateCatalogEntry<'static>],
    indent: &str,
    out: &mut String,
) {
    match node {
        EngineStateTreeNode::Leaf { entry_index } => {
            let entry = &catalog[*entry_index];
            out.push_str(&state_ref_luau(entry.capability, entry.value_type));
        }
        EngineStateTreeNode::Object(children) => {
            out.push_str("{\n");
            let child_indent = format!("{indent}  ");
            for (segment, child) in children {
                write!(out, "{child_indent}{segment}: ").unwrap();
                emit_luau_game_state_node(child, catalog, &child_indent, out);
                out.push_str(",\n");
            }
            write!(out, "{indent}}}").unwrap();
        }
    }
}

pub fn emit_luau_game_state_refs(out: &mut String) {
    let catalog = engine_state_catalog().expect("built-in engine-state catalog must be valid");
    out.push_str("--- Generated engine-owned state reference tree returned by `getGameState()`.\n");
    out.push_str("export type GameStateRefs = ");
    emit_luau_game_state_node(
        &EngineStateTreeNode::Object(catalog.tree().root().clone()),
        catalog.entries(),
        "",
        out,
    );
    out.push_str("\n\n");
    out.push_str(
        "--- Return immutable engine-state reference descriptors. Pure; no live state read.\n",
    );
    out.push_str("declare function getGameState(): GameStateRefs\n\n");
}

// Static type declarations for the Luau SDK library globals installed by
// the embedded `world.luau`, `entities/lights.luau`, `entities/emitters.luau`,
// `entities/fog_volumes.luau`, and `util/keyframes.luau` preludes. Appended to the generated
// `postretro.d.luau` so `luau-lsp` resolves the symbols without an explicit
// `require`. See: context/lib/scripting.md §7.
// Source of truth for this static block:
//   sdk/lib/world.luau
//   sdk/lib/entities/lights.luau
//   sdk/lib/entities/emitters.luau
//   sdk/lib/entities/fog_volumes.luau
//   sdk/lib/util/keyframes.luau
//   sdk/lib/data_script.luau  (embedded directly via include_str! in luau.rs)
//   sdk/lib/ui/{text,widgets,layout,tree,state}.luau
// Drift between this block and those files causes IDE types that don't match
// runtime behavior. Update this block whenever an SDK lib signature changes.

const LUAU_SDK_LIB_BLOCK: &str = include_str!("templates/sdk_lib.luau");

const LUAU_VIRTUAL_MODULE_TYPES: &str = include_str!("templates/virtual_module.luau");

pub fn luau_public_sdk_lib_block() -> String {
    // Runtime still evaluates the UI SDK chunks so `require("postretro/ui")`
    // can be populated from the internal export inventory. The root Luau
    // author-visible surface no longer promotes UI entries into `_G`, so the
    // generated declaration file must remove matching bare global declarations.
    let mut block = LUAU_SDK_LIB_BLOCK.to_string();
    remove_range(
        &mut block,
        "--- Build a state-crossing watcher.",
        "-- ---------------------------------------------------------------------------\n-- State-store declarations",
    );
    remove_doc_and_decl_line(&mut block, "declare function defineTheme(");
    remove_doc_and_decl_line(&mut block, "declare function getDesignTokens(");
    remove_doc_and_decl_line(&mut block, "declare function Text(");
    remove_doc_and_decl_line(&mut block, "declare function Panel(");
    remove_doc_and_decl_line(&mut block, "declare function Image(");
    remove_doc_and_decl_line(&mut block, "declare function Spacer(");
    remove_doc_and_decl_line(&mut block, "declare function Button(");
    remove_doc_and_decl_line(&mut block, "declare function Slider(");
    remove_doc_and_decl_line(&mut block, "declare function Bar(");
    remove_doc_and_decl_line(&mut block, "declare function Announce(");
    remove_doc_and_decl_line(&mut block, "declare function VStack(");
    remove_doc_and_decl_line(&mut block, "declare function HStack(");
    remove_doc_and_decl_line(&mut block, "declare function Grid(");
    remove_doc_and_decl_line(&mut block, "declare function Tree(");
    remove_doc_and_decl_line(&mut block, "declare function defineUiTree(");
    remove_range(
        &mut block,
        "--- Compose bind-only options onto a state ref",
        "--- Build `{ slot, equals }` for scalar state refs.",
    );
    remove_doc_and_decl_line(&mut block, "declare function stateEquals");
    remove_doc_and_decl_line(&mut block, "declare function createLocalState");
    remove_doc_and_decl_line(&mut block, "declare function Switch");
    remove_decl_line(&mut block, "declare ui:");
    block.push('\n');
    block.push_str(LUAU_VIRTUAL_MODULE_TYPES);
    block
}
