// TypeScript SDK type-definition emission.
// See: context/lib/scripting.md §7

use std::fmt::Write as _;

use super::common::{replace_range, rust_to_ts, string_enum_doc, try_remove_range};
use crate::engine_state_catalog::{
    EngineStateCapability, EngineStateTreeNode, EngineStateValueType, engine_state_catalog,
};
use crate::primitives_registry::{RegisteredType, TaggedVariant, TypeShape};

pub(super) const TS_HEADER: &str = "// Generated by `gen-script-types`. Do not edit by hand.\n";

/// Indent used for every line inside the `declare module` block.
pub(super) const TS_INDENT: &str = "  ";
/// Indent used for fields/variants inside a multi-line TS type body.
const TS_FIELD_INDENT: &str = "    ";

fn ts_doc_block(doc: &str, indent: &str, out: &mut String) {
    if doc.is_empty() {
        return;
    }
    writeln!(out, "{indent}/** {doc} */").unwrap();
}

pub(super) fn emit_ts_type(ty: &RegisteredType, out: &mut String) {
    if !matches!(&ty.shape, TypeShape::StringEnum { .. }) {
        ts_doc_block(ty.doc, TS_INDENT, out);
    }
    match &ty.shape {
        TypeShape::Brand { underlying } => {
            writeln!(
                out,
                "{TS_INDENT}export type {name} = {underlying} & {{ readonly __brand: \"{name}\" }};",
                name = ty.name,
            )
            .unwrap();
        }
        TypeShape::GenericBrand {
            type_param,
            underlying,
        } => {
            if ty.name == "StateValue" {
                writeln!(
                    out,
                    "{TS_INDENT}export type StateValue<{type_param}> = WritableStateRef<{type_param}>;",
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "{TS_INDENT}export type {name}<{type_param}> = {underlying} & {{ readonly __brand: \"{name}\" }};",
                    name = ty.name,
                )
                .unwrap();
            }
        }
        TypeShape::Struct { fields } => {
            let any_doc = fields.iter().any(|f| !f.doc.is_empty());
            if !any_doc {
                let body = fields
                    .iter()
                    .map(|f| format!("{}: {}", f.name, rust_to_ts(f.ty_name)))
                    .collect::<Vec<_>>()
                    .join("; ");
                writeln!(out, "{TS_INDENT}export type {} = {{ {body} }};", ty.name).unwrap();
            } else {
                writeln!(out, "{TS_INDENT}export type {} = {{", ty.name).unwrap();
                for f in fields {
                    ts_doc_block(f.doc, TS_FIELD_INDENT, out);
                    writeln!(
                        out,
                        "{TS_FIELD_INDENT}{}: {};",
                        f.name,
                        rust_to_ts(f.ty_name)
                    )
                    .unwrap();
                }
                writeln!(out, "{TS_INDENT}}};").unwrap();
            }
        }
        TypeShape::StringEnum { variants } => {
            let doc = string_enum_doc(ty.doc, variants);
            ts_doc_block(&doc, TS_INDENT, out);
            let any_doc = variants.iter().any(|v| !v.doc.is_empty());
            if !any_doc {
                let body = variants
                    .iter()
                    .map(|v| format!("\"{}\"", v.name))
                    .collect::<Vec<_>>()
                    .join(" | ");
                writeln!(out, "{TS_INDENT}export type {} = {body};", ty.name).unwrap();
            } else {
                writeln!(out, "{TS_INDENT}export type {} =", ty.name).unwrap();
                let last = variants.len() - 1;
                for (i, v) in variants.iter().enumerate() {
                    ts_doc_block(v.doc, TS_FIELD_INDENT, out);
                    let suffix = if i == last { ";" } else { "" };
                    writeln!(out, "{TS_FIELD_INDENT}| \"{}\"{suffix}", v.name).unwrap();
                }
            }
        }
        TypeShape::TaggedUnion {
            tag_field,
            value_field,
            flat,
            variants,
        } => {
            let render_variant = |v: &TaggedVariant| -> String {
                if *flat {
                    format!(
                        "({{ {tag_field}: \"{}\" }} & {})",
                        v.kind,
                        rust_to_ts(v.value_ty)
                    )
                } else {
                    format!(
                        "{{ {tag_field}: \"{}\"; {value_field}: {} }}",
                        v.kind,
                        rust_to_ts(v.value_ty)
                    )
                }
            };
            let any_doc = variants.iter().any(|v| !v.doc.is_empty());
            if !any_doc {
                let body = variants
                    .iter()
                    .map(&render_variant)
                    .collect::<Vec<_>>()
                    .join(" | ");
                writeln!(out, "{TS_INDENT}export type {} = {body};", ty.name).unwrap();
            } else {
                writeln!(out, "{TS_INDENT}export type {} =", ty.name).unwrap();
                let last = variants.len() - 1;
                for (i, v) in variants.iter().enumerate() {
                    ts_doc_block(v.doc, TS_FIELD_INDENT, out);
                    let suffix = if i == last { ";" } else { "" };
                    writeln!(out, "{TS_FIELD_INDENT}| {}{suffix}", render_variant(v)).unwrap();
                }
            }
        }
    }
}

pub(super) fn state_ref_ts(
    capability: EngineStateCapability,
    value_type: EngineStateValueType<'_>,
) -> String {
    let ref_ty = if capability == EngineStateCapability::Writable {
        "WritableStateRef"
    } else {
        "ReadonlyStateRef"
    };
    format!("{ref_ty}<{}>", value_type.to_ts())
}

fn emit_ts_game_state_node(
    node: &EngineStateTreeNode,
    catalog: &[crate::engine_state_catalog::EngineStateCatalogEntry<'static>],
    indent: &str,
    out: &mut String,
) {
    match node {
        EngineStateTreeNode::Leaf { entry_index } => {
            let entry = &catalog[*entry_index];
            out.push_str(&state_ref_ts(entry.capability, entry.value_type));
        }
        EngineStateTreeNode::Object(children) => {
            out.push_str("{\n");
            let child_indent = format!("{indent}  ");
            for (segment, child) in children {
                write!(out, "{child_indent}readonly {segment}: ").unwrap();
                emit_ts_game_state_node(child, catalog, &child_indent, out);
                out.push_str(";\n");
            }
            write!(out, "{indent}}}").unwrap();
        }
    }
}

pub(super) fn emit_ts_game_state_refs(out: &mut String) {
    let catalog = engine_state_catalog().expect("built-in engine-state catalog must be valid");
    out.push_str(
        "  /** Generated engine-owned state reference tree returned by `getGameState()`. */\n",
    );
    out.push_str("  export type GameStateRefs = ");
    emit_ts_game_state_node(
        &EngineStateTreeNode::Object(catalog.tree().root().clone()),
        catalog.entries(),
        "  ",
        out,
    );
    out.push_str(";\n\n");
    out.push_str(
        "  /** Return immutable engine-state reference descriptors. Pure; no live state read. */\n",
    );
    out.push_str("  export function getGameState(): GameStateRefs;\n\n");
}

// Static type declarations for the SDK library globals (`world`, `timeline`,
// `sequence`) and the capability-method handle interfaces installed by the
// prelude. The block is appended verbatim inside
// `declare module "postretro" { ... }` so authors can `import { world }
// from "postretro"`. See: context/lib/scripting.md §7.
// Source of truth for this static block:
//   sdk/lib/world.ts
//   sdk/lib/entities/lights.ts
//   sdk/lib/entities/emitters.ts
//   sdk/lib/entities/fog_volumes.ts
//   sdk/lib/util/keyframes.ts
//   sdk/lib/data_script.ts  (re-exported via index.ts)
//   sdk/lib/ui/{text,widgets,layout,tree,state}.ts
// Drift between this block and those files causes IDE types that don't match
// runtime behavior. Update this block whenever an SDK lib signature changes.

const TS_SDK_LIB_BLOCK: &str = include_str!("templates/sdk_lib.d.ts");

const TS_ROOT_UI_MANIFEST_TYPES: &str = include_str!("templates/root_ui_manifest.d.ts");

pub(super) fn ts_public_root_sdk_lib_block() -> String {
    // Task 1 of the UI SDK split makes `sdk/types/postretro.d.ts` the authority
    // for the public root `postretro` module. `sdk/lib/prelude.ts` may still
    // export UI names solely to install QuickJS globals while the compiler strips
    // imports without alias rewriting; those names must not leak into the root
    // declaration block generated here.
    let mut block = TS_SDK_LIB_BLOCK.to_string();
    try_remove_range(
        &mut block,
        "  /** Build a state-crossing watcher.",
        "  // -------------------------------------------------------------------------\n  // State-store declarations.",
    );
    replace_range(
        &mut block,
        "  // -------------------------------------------------------------------------\n  // UI theme helpers.",
        "  /** Pure identity builder for entity-type descriptors.",
        TS_ROOT_UI_MANIFEST_TYPES,
    );
    block
}

const TS_UI_SDK_MODULE_BLOCK: &str = include_str!("templates/ui_sdk_module.d.ts");

pub(super) fn ts_ui_sdk_module_block() -> &'static str {
    TS_UI_SDK_MODULE_BLOCK
}
