[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Development workflow commands for Postretro"
license.workspace = true

[dependencies]
postretro-level-compiler = { workspace = true }
postretro-level-format = { workspace = true, features = ["gltf-resolve"] }
postretro-model = { workspace = true }
glam = { workspace = true }
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
