// Generated by `gen-script-types`. Do not edit by hand.
declare module "postretro" {
  export type EntityId = number & { readonly __brand: "EntityId" };

  export type Vec3 = { x: number; y: number; z: number };

  export type EulerDegrees = { pitch: number; yaw: number; roll: number };

  export type Transform = { position: Vec3; rotation: EulerDegrees; scale: Vec3 };

  export type ComponentKind = "Transform";

  export type ComponentValue = { kind: "Transform"; value: Transform };

  export type ScriptEvent = { kind: string; payload: unknown };

  export type ScriptCallContext = {
    /** Seconds since the previous tick. */
    delta: number;
    /** Seconds since level load; monotonic within a level. */
    time: number;
  };

  /** Despawns a previously-spawned entity. Errors if the id is stale. */
  export function despawn_entity(id: EntityId): void;

  /** Broadcasts an event to all listeners; drains at end of game logic. */
  export function emit_event(event: ScriptEvent): void;

  /** Returns true if the entity id refers to a live entity. */
  export function entity_exists(id: EntityId): boolean;

  /** Reads a component of the given kind from an entity. */
  export function get_component(id: EntityId, kind: ComponentKind): ComponentValue;

  /** Register a handler for an engine event. Currently accepts "levelLoad" or "tick". */
  export function registerHandler(event: string, handler: (ctx?: ScriptCallContext) => void): void;

  /** Sends an event to a single entity; drains at end of game logic. */
  export function send_event(target: EntityId, event: ScriptEvent): void;

  /** Writes a component of the given kind onto an entity. */
  export function set_component(id: EntityId, kind: ComponentKind, value: ComponentValue): void;

  /** Spawns a new entity with the given transform and returns its id. */
  export function spawn_entity(transform: Transform): EntityId;
}
