// Generated by `gen-script-types`. Do not edit by hand.
declare module "postretro" {
  export type EntityId = number & { readonly __brand: "EntityId" };

  export type StateValue<T> = WritableStateRef<T>;

  export type Vec3 = { x: number; y: number; z: number };

  export type EulerDegrees = { pitch: number; yaw: number; roll: number };

  export type Transform = { position: Vec3; rotation: EulerDegrees; scale: Vec3 };

  /** Valid values: `transform`, `light`, `billboard_emitter`, `particle_state`, `sprite_visual`, `fog_volume`. */
  export type ComponentKind = "transform" | "light" | "billboard_emitter" | "particle_state" | "sprite_visual" | "fog_volume";

  export type ComponentValue = ({ kind: "transform" } & Transform) | ({ kind: "light" } & LightComponent) | ({ kind: "billboard_emitter" } & BillboardEmitterComponent) | ({ kind: "particle_state" } & ParticleState) | ({ kind: "sprite_visual" } & SpriteVisual) | ({ kind: "fog_volume" } & FogVolumeComponent);

  /** Authored dynamic-light preset attached to `EntityTypeDescriptor.components.light`. Field names are snake_case on the script surface. Descriptor-spawned lights are runtime-only and do not participate in baked indirect lighting. */
  export type LightDescriptor = {
    /** Linear RGB light color multiplier. Components are conventionally in [0, 1], though HDR values above 1 are accepted. */
    color: Vec3;
    /** Unitless brightness multiplier. Must be finite and ≥ 0; 0 produces no light. */
    intensity: number;
    /** Falloff range in metres. Must be finite and ≥ 0; 0 gives the light no spatial reach. */
    range: number;
    /** Authoring hint retained in the descriptor. Descriptor-spawned lights are currently always materialized as dynamic because they cannot contribute to baked lighting. */
    is_dynamic: boolean;
  };

  /** How a fade *into* an animation state takes over when another fade is already in flight. Absent in a descriptor defaults to `"smooth"`. Valid values: `smooth`, `snap`. */
  export type InterruptPolicy =
    /** Capture the in-flight blended pose once and blend the new fade from it — no discontinuity. */
    | "smooth"
    /** Blend the new fade from the interrupted state's clip; the in-flight blend drops — a deliberate, fade-window-bounded pop. */
    | "snap";

  /** One declared animation state: a named clip plus loop and crossfade policy. `clip` is resolved against the model's clip metadata at level load. */
  export type AnimationStateDescriptor = {
    /** Clip name this state plays. Must be non-empty; resolved against the model's clips at level load. */
    clip: string;
    /** Whether the clip loops. Optional; defaults to false. */
    loop?: boolean;
    /** Crossfade duration into this state, in milliseconds. Optional; must be finite and >= 0. Defaults to 150 ms. */
    crossfadeMs?: number;
    /** How a fade into this state takes over an in-flight fade. Optional; defaults to "smooth". */
    interrupt?: InterruptPolicy;
  };

  /** Authored mesh component preset attached to `EntityTypeDescriptor.components.mesh`. A descriptor carrying `components.mesh` is directly map-placeable via `canonicalName`. `model` is the skinned-model handle; `animations` declares the per-entity logical animation-state map (state name → clip + loop + crossfade + interrupt). When `animations` is present it must be non-empty and `defaultState` must name a declared state; omit both for a stateless mesh. */
  export type MeshDescriptor = {
    /** Skinned-model handle this entity renders. Must be non-empty. */
    model: string;
    /** Declared animation states keyed by author-defined state name (e.g. idle/locomotion/attack/death). Optional; when present, must be non-empty and accompanied by a `defaultState` naming one of these states. Omit for a stateless mesh. */
    animations?: { readonly [state: string]: AnimationStateDescriptor };
    /** The state entered at spawn. Required exactly when `animations` is present; must name a declared state. */
    defaultState?: string;
  };

  /** Entity archetype registered through `ModManifest.entities`. `defineEntity()` is a typed identity helper for constructing this object. The descriptor is engine-global and survives level unloads. */
  export type EntityTypeDescriptor = {
    /** Stable archetype name used by map classname routing and descriptor references. Required for direct map placement and for weapon descriptors referenced by `defaultWeapon`; omit only for archetypes that are never addressed by name. */
    canonicalName?: string;
    /** The `canonicalName` of a registered weapon archetype to instantiate and equip when this descriptor is selected by a `player_spawn` marker. Other spawn paths ignore this key. */
    defaultWeapon?: string;
    /** Optional component presets. Direct map placement materializes light, emitter, and movement presets; `player_spawn` does the same and may also equip `defaultWeapon`; weapon presets materialize on the separate wieldable entity created by that route. */
    components?: EntityTypeComponents;
  };

  /** Engine-managed billboard-particle emitter preset. Field names are snake_case on the script surface. Prefer the SDK `emitter()` builder or a preset such as `smokeEmitter()` when defaults are suitable. */
  export type BillboardEmitterComponent = {
    /** Continuous spawn rate in particles/sec. Must be finite and ≥ 0; 0 disables continuous spawning. */
    rate: number;
    /** Optional one-time particle count emitted when the component is materialized. null disables the burst. */
    burst: number | null;
    /** Random angular spread around `velocity`, in radians. Must be finite and ≥ 0; 0 emits in one direction. */
    spread: number;
    /** Lifetime of each particle in seconds. Must be finite and > 0. */
    lifetime: number;
    /** Initial particle velocity vector in metres/sec before random spread is applied. */
    velocity: Vec3;
    /** Unitless gravity multiplier using `verticalAcceleration = worldGravity * -buoyancy`: -1 falls at normal gravity, 0 floats, values between -1 and 0 sink more slowly, and positive values rise. */
    buoyancy: number;
    /** Velocity damping coefficient in 1/sec. Must be finite and ≥ 0; 0 preserves velocity apart from buoyancy. */
    drag: number;
    /** Non-empty normalized-lifetime curve of billboard size multipliers. Samples are evenly spaced from spawn to death. */
    size_over_lifetime: ReadonlyArray<number>;
    /** Non-empty normalized-lifetime curve of opacity multipliers. Samples are evenly spaced from spawn to death. */
    opacity_over_lifetime: ReadonlyArray<number>;
    /** RGB multiplier applied to every emitted particle. Components are conventionally in [0, 1], with values above 1 available for HDR tinting. */
    color: Vec3;
    /** Non-empty sprite/material identifier resolved by the billboard renderer. */
    sprite: string;
    /** Initial billboard angular velocity in radians/sec. Positive and negative values rotate in opposite directions. */
    spin_rate: number;
    /** Optional spin-rate tween. null keeps `spin_rate` constant. */
    spin_animation: SpinAnimation | null;
  };

  /** Spin-rate tween carried by a billboard emitter and consumed by `setSpinRate`. */
  export type SpinAnimation = {
    /** Tween duration in seconds. Must be finite and > 0. */
    duration: number;
    /** Non-empty curve of spin rates in radians/sec, sampled evenly across `duration`. */
    rate_curve: ReadonlyArray<number>;
  };

  /** Animation curves attached to a fog volume by the `setFogAnimation` reaction primitive. Four independent channels share `periodMs` / `phase` / `playCount`: `density` modulates volumetric density, `saturation` modulates SH-irradiance saturation, `minBrightness` modulates the scatter brightness floor, and `lightRange` scales how far lights reach inside the fog. At least one curve must be present when `playCount` is finite — otherwise the animation has nothing to settle to. `phase` is normalized into `[0, 1)`. `playCount = null` loops forever; finite counts have the bridge write back each channel's final keyframe as static state on completion. There is no `startActive` flag — fog has no GPU descriptor for the curve, so absence (`null`) is the only inactive state. */
  export type FogAnimation = {
    /** Total period of the loop, in milliseconds. */
    periodMs: number;
    /** Starting phase in [0.0, 1.0). Values outside this range are normalized via rem_euclid. */
    phase: number | null;
    /** Total full periods to play; null loops forever. */
    playCount: number | null;
    /** Per-sample density curve. null leaves the static density unchanged. */
    density: ReadonlyArray<number> | null;
    /** Per-sample saturation curve. null leaves the static saturation unchanged. */
    saturation: ReadonlyArray<number> | null;
    /** Per-sample animation curve for the `min_brightness` channel (scatter brightness floor). null leaves the static min_brightness unchanged. Each sample clamped to `[0, +∞)`; empty curve is rejected. */
    minBrightness: ReadonlyArray<number> | null;
    /** Per-sample animation curve for the `light_range` channel (scales how far lights reach inside this fog). null leaves the static light_range unchanged. Each sample must be strictly positive and finite; non-positive or non-finite samples clamp to `0.001`; empty curve is rejected. */
    lightRange: ReadonlyArray<number> | null;
  };

  /** Script-facing fog-volume component shape. Carried by `FogVolume` ECS entities; the AABB is baked at level load and lives in the FogVolumeBridge side-table — it is not exposed here because it is not runtime-settable. */
  export type FogVolumeComponent = {
    /** Volumetric fog density inside the AABB. */
    density: number;
    /** How much the fog lights up near light sources. 0 = stays dark even under bright lights, 1 = picks up full light color. Raise for misty glow, lower for thick opaque smoke. */
    glow: number;
    /** Edge softness in world units: 0 = hard cutoff at the brush face, larger = wider linear ramp inward from each face. */
    edgeSoftness: number;
    /** Radial falloff exponent. Consulted by the radial (`fog_lamp`, `fog_tube`) and ellipsoid (axis-aligned `fog_volume`) shader paths; stored but ignored by the plane-sweep (non-axis-aligned `fog_volume`) path. */
    falloff: number;
    /** Per-volume RGB scatter multiplier. Default `[1.0, 1.0, 1.0]`. */
    tint: readonly [number, number, number];
    /** Saturation of transmitted SH irradiance: 0 = greyscale, 1 = natural, >1 = boosted. Default 1.0. */
    saturation: number;
    /** Floor on per-volume scatter brightness. Clamped to `[0, +∞)`. Default 0.0. */
    minBrightness: number;
    /** Scales how far lights reach inside this fog. 1.0 = same range as open air, 2.0 = double range, 0.5 = half range. Strictly positive; clamps to 0.001. Default 1.0. */
    lightRange: number;
    /** Optional animation carrying any combination of density, saturation, minBrightness, and lightRange curves. null holds the static state. */
    animation: FogAnimation | null;
  };

  /** Entity handle returned by `world.query` when filtering for fog-volume entities. */
  export type FogVolumeEntity = {
    id: EntityId;
    /** Volume center at query time (AABB midpoint, baked at level load). */
    position: Vec3;
    /** The entity's tags at query time. Empty array if untagged. */
    tags: ReadonlyArray<string>;
    /** Full fog-volume component snapshot at query time. */
    component: FogVolumeComponent;
  };

  /** Component presets carried by `EntityTypeDescriptor.components`. Each key is optional and independent; present values are validated when the mod manifest loads. */
  export type EntityTypeComponents = {
    /** Dynamic-light preset materialized on each spawned instance. */
    light?: LightDescriptor | null;
    /** Billboard-particle emitter preset materialized on each spawned instance. */
    emitter?: BillboardEmitterComponent | null;
    /** Player movement, collision capsule, and first-person view-feel preset. */
    movement?: PlayerMovementDescriptor | null;
    /** Weapon tuning preset. Weapon archetypes are instantiated as wieldable entities when referenced by `defaultWeapon`. */
    weapon?: WeaponDescriptor | null;
    /** Animated skinned-mesh preset: model handle plus an optional per-state animation map. A descriptor carrying this is directly map-placeable by canonicalName. */
    mesh?: MeshDescriptor | null;
    /** Hit points plus an optional hitscan hitbox. A descriptor carrying this is directly map-placeable by canonicalName. */
    health?: HealthDescriptor | null;
    /** AI brain preset: detection/attack/leash ranges, attack tuning, move speed, despawn delay, EXP reward, and the logical-state → mesh animation-state map. Materializes a brain plus a navigation agent at spawn. Rides on health+mesh for map placement; it does not itself make a descriptor placeable. */
    ai?: AiDescriptor | null;
  };

  /** Valid values: `semi`, `auto`. */
  export type FireMode =
    /** One shot per press. */
    | "semi"
    /** Continuous fire while held. */
    | "auto";

  /** Valid values: `hitscan`. */
  export type ResolutionMode =
    /** Resolve instantly against the static-world collision ray. */
    | "hitscan";

  /** Authored weapon component preset. Descriptor-owned tuning data; maps do not override these params. Spawn-time player equip materializes a separate wieldable instance entity from this descriptor. */
  export type WeaponDescriptor = {
    /** Base damage payload per resolved shot. Must be finite and ≥ 0. */
    damage: number;
    /** Maximum hitscan distance in metres. Must be finite and > 0. */
    range: number;
    /** Minimum interval between shots in milliseconds. Must be finite and > 0. */
    fireRateMs: number;
    /** Semi or automatic input gate. */
    fireMode: FireMode;
    /** Shot resolution mode. Currently supports hitscan only. */
    resolution: ResolutionMode;
  };

  /** One world-aligned AABB hitbox. Carrying one makes the entity hitscan-targetable. `halfExtents` is the box half-size on each axis; `offset` shifts the box center from the entity's transform position. */
  export type HitboxDescriptor = {
    /** Box half-size on each axis, in metres. Each element must be finite and > 0. */
    halfExtents: readonly [number, number, number];
    /** Center offset from the entity's transform position, in metres. Each element must be finite. Optional; defaults to [0, 0, 0]. */
    offset?: readonly [number, number, number];
  };

  /** Authored health component preset attached to `EntityTypeDescriptor.components.health`. `max` is the entity's hit-point ceiling; the optional `hitbox` makes the entity hitscan-targetable (one world-aligned AABB, fixed per archetype). Materializes into a Health component with `current == max` at spawn. */
  export type HealthDescriptor = {
    /** Maximum hit points. Must be finite and >= 1.0; `current` initializes to this value at spawn. */
    max: number;
    /** Optional hitscan hitbox. Present ⇒ the entity can be ray-targeted by weapons; absent ⇒ it cannot. */
    hitbox?: HitboxDescriptor;
    /** Per-skeletal-zone damage multipliers, tag → factor (e.g. `{ head: 1.5 }`). A shot on a tagged zone scales the weapon's payload by this factor; an absent zone or unlisted tag applies 1.0. Each factor must be finite and >= 0. Optional; defaults to empty. */
    zoneMultipliers?: { readonly [tag: string]: number };
  };

  /** The closed logical-state → animation-state name mapping carried by `AiDescriptor.states`. Each value names a state declared in the entity's `components.mesh.animations`; the brain switches the mesh to the matching state when it enters that logical state. All four keys are required and the set is closed (no other keys allowed). */
  export type AiStateNames = {
    /** Mesh state played while the brain is idle (no target). Must name a declared mesh animation state. */
    idle: string;
    /** Mesh state played while the brain is alerted and pursuing a target (the chase/locomotion state). Must name a declared mesh animation state. */
    alert: string;
    /** Mesh state played while the brain attacks. Must name a declared mesh animation state. */
    attack: string;
    /** Mesh state played when the brain dies. Must name a declared mesh animation state. */
    death: string;
  };

  /** Authored AI brain component preset attached to `EntityTypeDescriptor.components.ai`. Descriptor-owned tuning: maps never override these. Materializes the engine-owned brain (logical state + timers) and a movable navigation agent at spawn. Distances are in metres, times in milliseconds, `moveSpeed` in metres/sec. The `states` block links the brain's logical states to mesh animation states; that cross-component mapping is validated at spawn (the ai block cannot see the mesh block at its own parse). */
  export type AiDescriptor = {
    /** Distance at which the brain notices a target and leaves idle, in metres. Must be finite and > 0. */
    detectionRange: number;
    /** Distance within which the brain attacks rather than pursues, in metres. Must be finite and > 0. */
    attackRange: number;
    /** Distance from its origin past which the brain disengages and returns, in metres. Must be finite and > 0. */
    leashRange: number;
    /** Damage dealt per attack. Must be finite and >= 0 (a negative value would heal the target through the damage chokepoint). */
    attackDamage: number;
    /** Minimum interval between attacks, in milliseconds. Must be finite and > 0. */
    attackCooldownMs: number;
    /** Pursuit movement speed in metres/sec, seeding the navigation agent. Must be finite and > 0. */
    moveSpeed: number;
    /** Delay between death and despawn, in milliseconds (lets the death animation play out). Must be finite and > 0. */
    deathDespawnMs: number;
    /** Closed logical-state → mesh animation-state name mapping (idle / alert / attack / death). Each value must name a state declared in `components.mesh.animations`; validated at spawn. */
    states: AiStateNames;
  };

  /** Authored player-movement preset. `capsule`, `ground`, `air`, and `fall` are required. `dash`, `crouch`, and `viewFeel` are opt-in features; `forgiveness` has engine defaults when omitted. Distances use metres and time uses seconds unless a key is suffixed `Ms`. */
  export type PlayerMovementDescriptor = {
    /** Required collision capsule and camera attachment geometry, in metres. */
    capsule: CapsuleParams;
    /** Required on-ground speed, acceleration, stepping, and slope limits. */
    ground: GroundParams;
    /** Required jump and mid-air steering parameters. */
    air: AirParams;
    /** Required terminal falling-speed limit. */
    fall: FallParams;
    /** Optional dash tuning. When omitted, dash is disabled. When present, all of its fields are required. */
    dash?: DashParams;
    /** Optional input-forgiveness tuning (coyote time + jump buffer). When the whole object is omitted, the documented engine defaults apply (~100ms each). When present, each field is itself optional and falls back to its engine default; 0 disables that grace. */
    forgiveness?: ForgivenessParams;
    /** Optional crouch tuning. When omitted, crouch is disabled. When present, all of its fields are required. */
    crouch?: CrouchParams;
    /** Optional first-person view-feel tuning (head bob, strafe tilt, ambient sway). A render-only camera effect. When omitted, view feel is disabled. When present, each of `bob`/`tilt`/`sway` is independently optional. */
    viewFeel?: ViewFeelParams;
    /** Optional. Stuck-stop deadzone enable flag. When true (default), the slide loop zeroes horizontal velocity and rolls back XZ position when contradictory wall normals (≥60° apart) are seen within the same tick AND net horizontal displacement is below `stuckStopThreshold`. Suppresses orbital jitter in interior corners. Default true. */
    stuckStopEnabled?: boolean;
    /** Optional. Horizontal-displacement threshold in metres that gates the deadzone. Must be finite and ≥ 0. Default 1.0e-3. */
    stuckStopThreshold?: number;
  };

  /** Player collision capsule. `halfHeight` is the cylinder half-height; total capsule height is `2 * (halfHeight + radius)`. `eyeHeight` is the camera attachment point measured upward from the capsule center. */
  export type CapsuleParams = {
    /** Capsule radius in metres. Must be finite and > 0. */
    radius: number;
    /** Cylinder half-height in metres, excluding the rounded caps. Must be finite and > 0. */
    halfHeight: number;
    /** Camera attachment point measured upward from the capsule center in metres. Must be finite and lie in (0, halfHeight + radius]. */
    eyeHeight: number;
  };

  /** On-ground locomotion parameters. `maxSlope` is in degrees on the wire and converted to a cosine at materialization. */
  export type GroundParams = {
    /** Horizontal walk, run, and crouch target speeds in metres/sec. */
    speed: SpeedParams;
    /** Ground acceleration in metres/sec². Must be finite and ≥ 0. */
    accel: number;
    /** Maximum automatic step-up height in metres. Must be finite and ≥ 0; 0 disables stepping. */
    stepHeight: number;
    /** Steepest walkable surface angle in degrees. Must be finite and lie in [0, 90]. */
    maxSlope: number;
  };

  /** Walk, run, and crouch ground speeds in metres/sec. The movement tick uses `run` while sprint is held, `crouch` while crouched, and `walk` otherwise, applied omnidirectionally. All required and must be finite and ≥ 0. */
  export type SpeedParams = {
    /** Steady-state horizontal speed in metres/sec when not sprinting. Must be finite and ≥ 0. */
    walk: number;
    /** Steady-state horizontal speed in metres/sec while sprint is held. Must be finite and ≥ 0. */
    run: number;
    /** Steady-state horizontal speed in metres/sec while crouched. Must be finite and ≥ 0. */
    crouch: number;
  };

  /** Mid-air control parameters. `forwardSteer` blends forward steering authority between 0 (pure strafe-only Quake air control) and 1 (full forward authority). `jumpCeiling` is required when `jumps > 0`. */
  export type AirParams = {
    /** Forward steering authority in [0, 1]. */
    forwardSteer: number;
    /** Air acceleration in metres/sec². Must be finite and ≥ 0. */
    accel: number;
    /** Horizontal speed cap in metres/sec that air acceleration can push toward. Must be finite and ≥ 0. */
    maxControlSpeed: number;
    /** Permit chained jumps on landing without releasing the jump input. */
    bunnyHop: boolean;
    /** Additional jumps allowed in air after the initial ground jump. 0 disables air jumps. */
    jumps: number;
    /** Upward velocity in metres/sec applied by a ground jump. Must be finite and ≥ 0. */
    jumpVelocity: number;
    /** Air-jump activation threshold in metres/sec: an air jump may fire only while current vertical velocity is ≤ this value, after which velocity is set to `jumpVelocity`. Required when `jumps > 0`; 0 is conventional when air jumps are disabled. */
    jumpCeiling: number;
  };

  /** Falling parameters. */
  export type FallParams = {
    /** Maximum downward fall speed magnitude in metres/sec. Must be finite and > 0. */
    terminalVelocity: number;
  };

  /** Dash tuning. Optional on `PlayerMovementDescriptor` — when omitted, dash is disabled. When present, all fields are required and validated. */
  export type DashParams = {
    /** Impulse magnitude applied on dash in metres/sec. A literal must be finite > 0. Accepts a runtime expression, evaluated at dash entry. */
    boostSpeed: number | RuntimeValue;
    /** Fraction of pre-dash momentum folded into the dash, unitless in [0, 1]. Accepts a runtime expression, evaluated at dash entry. */
    momentumRetention: number | RuntimeValue;
    /** In-dash steering authority, unitless in [0, 1]. Accepts a runtime expression, evaluated per tick during the dash. */
    steerControl: number | RuntimeValue;
    /** Decay rate of the dash impulse in metres/sec². A literal must be finite and ≥ 0. Accepts a runtime expression, evaluated per tick during the dash. */
    dashDrag: number | RuntimeValue;
    /** Cooldown between dashes in milliseconds. A literal must be finite and ≥ 0. Accepts a runtime expression, evaluated at dash entry. */
    cooldownMs: number | RuntimeValue;
    /** Number of air dashes allowed before landing. */
    airDashes: number;
    /** Whether the dash preserves the pre-dash vertical velocity. Accepts a runtime expression, evaluated at dash entry. */
    preserveVertical: boolean | RuntimeValue;
  };

  /** Crouch tuning. Optional on `PlayerMovementDescriptor` — when omitted, crouch is disabled. When present, all fields are required and validated. */
  export type CrouchParams = {
    /** Crouched capsule half-height in metres. Must be finite > 0. */
    halfHeight: number;
    /** Crouched camera attachment point measured upward from the capsule center in metres. Must lie in (0, crouched halfHeight + radius]. */
    eyeHeight: number;
    /** Rate the capsule interpolates between standing and crouched extents, per-sec. Must be finite > 0. */
    transitionRate: number;
  };

  /** First-person view-feel tuning: a render-only camera effect bundle (head bob, strafe tilt, ambient sway). Optional on `PlayerMovementDescriptor` — when omitted, view feel is disabled. When present, each of `bob`/`tilt`/`sway` is independently optional; an absent sub-object disables that motion. */
  export type ViewFeelParams = {
    /** Optional head-bob tuning. When omitted, head bob is disabled. When present, all of its fields are required except `groundedOnly`. */
    bob?: BobParams;
    /** Optional strafe-tilt tuning. When omitted, strafe tilt is disabled. When present, all of its fields are required except `groundedOnly`. */
    tilt?: TiltParams;
    /** Optional ambient-sway tuning. When omitted, ambient sway is disabled. When present, all of its fields are required except `groundedOnly`. */
    sway?: SwayParams;
  };

  /** Distance-phased head-bob tuning. Vertical and lateral motion have independent cadences. All fields are required except `groundedOnly`, which defaults to true. */
  export type BobParams = {
    /** Vertical oscillation cycles per metre travelled. Must be finite and > 0; larger values produce quicker up/down steps. */
    verticalFrequency: number;
    /** Lateral oscillation cycles per metre travelled. Must be finite and > 0. Half of `verticalFrequency` produces the classic one side-to-side cycle per two vertical cycles. */
    lateralFrequency: number;
    /** Peak vertical eye displacement in metres. Must be finite and ≥ 0; 0 disables vertical displacement. */
    verticalAmplitude: number;
    /** Peak side-to-side eye displacement in metres. Must be finite and ≥ 0; 0 disables lateral displacement. */
    lateralAmplitude: number;
    /** Horizontal speed in metres/sec at or below which bob outputs zero and holds both phases. Must be finite and ≥ 0; amplitude eases in over the next 1 m/s. */
    speedThreshold: number;
    /** When true, airborne bob outputs zero and holds both phases. Optional; defaults to true. */
    groundedOnly?: boolean;
  };

  /** Strafe-tilt tuning. When present on `viewFeel`, all fields are required and validated except `groundedOnly`, which is optional and defaults to true. */
  export type TiltParams = {
    /** Maximum tilt angle in degrees. Must be finite in [0, 90]. */
    maxAngle: number;
    /** Lateral speed in metres/sec at which tilt reaches `maxAngle`. Must be finite and > 0. */
    speedReference: number;
    /** Spring natural-frequency tuning in 1/sec. Must be finite and > 0; larger values track direction changes more quickly. */
    tension: number;
    /** Whether tilt applies only while grounded. Optional; defaults to true. */
    groundedOnly?: boolean;
  };

  /** Ambient-sway tuning. When present on `viewFeel`, all fields are required and validated except `groundedOnly`, which is optional and defaults to false. */
  export type SwayParams = {
    /** Sway amplitude in degrees. Must be finite and ≥ 0. */
    amplitude: number;
    /** Sway oscillation frequency in Hz. Must be finite > 0. */
    frequency: number;
    /** Additional sway multiplier per metre/sec of horizontal speed. Must be finite and ≥ 0; 0 makes sway independent of movement speed. */
    speedScale: number;
    /** Whether sway applies only while grounded. Optional; defaults to false. */
    groundedOnly?: boolean;
  };

  /** Input-forgiveness tuning (coyote time + jump buffering). Optional on `PlayerMovementDescriptor` — when the whole `forgiveness` object is omitted, the documented engine defaults apply. When present, each field is itself optional and falls back to its engine default; an explicit 0 disables that grace independently. Both windows are in milliseconds. */
  export type ForgivenessParams = {
    /** Coyote-time window in milliseconds: a grounded jump is permitted for this long after leaving a ledge (with no prior jump). 0 disables coyote time. Default 100.0. */
    coyoteMs?: number;
    /** Jump-buffer window in milliseconds: a jump pressed this long before landing fires on the landing tick. 0 disables jump buffering. Default 100.0. */
    jumpBufferMs?: number;
  };

  /** A UI tree registered through `ModManifest.uiTrees` (or `LevelManifest.uiTrees`). Pairs a registry `name` with an `AnchoredTree` placement envelope and the `alwaysOn` registration flag. A malformed entry is logged and skipped at load time. */
  export type ModUiTree = {
    /** Registry name the render path resolves the tree by. Required. */
    name: string;
    /** The placement envelope + widget tree (the value produced by the `Tree` factory). Required. */
    tree: AnchoredTreeDescriptor;
    /** Whether the tree composes as a per-frame base layer (e.g. the HUD: always rendered) rather than only when explicitly pushed onto the modal stack. Optional; defaults to false. */
    alwaysOn?: boolean;
  };

  /** One map listed in `ModManifest.maps`. Use `defineMapCatalog([...])` for a typed construction site; the returned array keeps this exact wire shape. The catalog is committed during mod init and is available before any level loads. */
  export type ModMapEntry = {
    /** Stable logical map handle used by `loadLevel(id)`, frontend `backgroundLevel`, and future references. Required; exact string match. */
    id: string;
    /** PRL path authored relative to the content root, such as `base/maps/e1m1.prl`. Required. */
    path: string;
    /** Display name shown to players in catalog-driven UI. Required. */
    name: string;
    /** Authoritative classification tags for filtering plus `levels` selection on mod-global reactions and crossings. Optional; missing/null normalizes to empty. */
    tags?: ReadonlyArray<string>;
  };

  /** Static camera pose used while a mod frontend menu is presented. All fields are required when `ModManifest.frontend` is present. */
  export type MenuCamera = {
    /** World-space camera position in metres as `[x, y, z]`. Required. */
    position: readonly [number, number, number];
    /** Camera yaw in radians. Required. */
    yaw: number;
    /** Camera pitch in radians. Required. */
    pitch: number;
  };

  /** Mod frontend declaration. Selects the startup menu tree, optional background catalog map, and static menu camera pose. Omit `frontend` to use the engine fallback menu. */
  export type Frontend = {
    /** UI tree registry name presented as the frontend menu. Required; if the name is not registered, the engine fallback frontend is shown. */
    menuTree: string;
    /** Map catalog id to load behind the frontend menu. Optional; omit for no backdrop level. */
    backgroundLevel?: string;
    /** Static menu camera pose. Required. */
    camera: MenuCamera;
  };

  /** Theme token maps supplied via `ModManifest.theme`. Three category-scoped maps: colors (linear-RGBA), fonts (registered family name), spacing (logical px). Each is optional; overrides merge per-token into the engine default. */
  export type ThemeTokens = {
    /** Color tokens: token name → linear-RGBA `[r, g, b, a]`. Optional. */
    colors?: { readonly [token: string]: readonly [number, number, number, number] };
    /** Font tokens: token name → registered family name. Optional. */
    fonts?: { readonly [token: string]: string };
    /** Spacing tokens: token name → logical px. Optional. */
    spacing?: { readonly [token: string]: number };
  };

  /** Mod manifest consumed from `start-script.ts`'s default export or `start-script.luau`'s chunk return. `defineMod(config)` is a pure typed identity helper for this object; the engine commits its data only after manifest validation succeeds. */
  export type ModManifest = {
    /** Human-readable mod name used for diagnostics and UI. Required. */
    name: string;
    /** Engine-global entity-type registrations. Optional; survive level unload and are committed only after the manifest validates. */
    entities?: ReadonlyArray<EntityTypeDescriptor>;
    /** Script-registered UI trees (name + `AnchoredTree` + `alwaysOn`). Optional; malformed entries are logged and skipped without aborting boot. */
    uiTrees?: ReadonlyArray<ModUiTree>;
    /** Theme token overrides (colors/fonts/spacing). Optional; merged per-token into the engine default. */
    theme?: ThemeTokens;
    /** Font assets: family name → TTF asset path. Optional; changing custom font assets requires an engine restart. */
    fonts?: { readonly [token: string]: string };
    /** Pre-load-discoverable map catalog. Optional; use catalog ids with `loadLevel(id)` and `frontend.backgroundLevel`. */
    maps?: ReadonlyArray<ModMapEntry>;
    /** Mod-defined frontend menu declaration. Optional; omission clears the mod frontend and presents the engine fallback menu. */
    frontend?: Frontend;
    /** Engine-global reaction definitions. Optional; survive level unload and compose into active level behavior by `levels` tag selectors. */
    reactions?: ReadonlyArray<NamedReactionDescriptor>;
    /** Engine-global state-crossing watchers. Optional; survive level unload and compose into active level behavior by `levels` tag selectors. */
    crossings?: ReadonlyArray<CrossingDescriptor>;
    /** Engine-global state-store declarations returned by `defineStore(...).declaration`. Optional; commit atomically after the manifest validates and preserve existing values when the schema is identical. */
    stores?: ReadonlyArray<StoreDeclaration>;
  };

  /** Valid values: `Point`, `Spot`, `Directional`. */
  export type LightKind = "Point" | "Spot" | "Directional";

  /** Valid values: `Linear`, `InverseDistance`, `InverseSquared`. */
  export type FalloffKind = "Linear" | "InverseDistance" | "InverseSquared";

  export type LightAnimation = {
    /** Total period of the loop, in milliseconds. */
    periodMs: number;
    /** Starting phase in [0.0, 1.0). Values outside this range are normalized via rem_euclid. */
    phase: number | null;
    /** Total full periods to play; null loops forever. */
    playCount: number | null;
    /** Whether the animation starts in the active state. null defaults to true; false mirrors the FGD `_start_inactive` flag. */
    startActive: boolean | null;
    /** Per-sample brightness curve. */
    brightness: ReadonlyArray<number> | null;
    /** Per-sample color curve. Only valid on dynamic lights. */
    color: ReadonlyArray<Vec3> | null;
    /** Per-sample direction curve. Non-unit samples are silently normalized. */
    direction: ReadonlyArray<Vec3> | null;
  };

  export type LightComponent = { origin: Vec3; lightType: LightKind; intensity: number; color: Vec3; falloffModel: FalloffKind; falloffRange: number; coneAngleInner: number | null; coneAngleOuter: number | null; coneDirection: Vec3 | null; isDynamic: boolean; animation: LightAnimation | null };

  /** Component-name literals accepted by `worldQuery` and the `world.query` SDK wrapper. New queryable component types extend this union. Valid values: `light`, `transform`, `emitter`, `fog_volume`, `particle`, `sprite_visual`. */
  export type WorldQueryComponent =
    | "light"
    | "transform"
    | "emitter"
    | "fog_volume"
    /** Always returns []. Engine-managed; scripts never iterate individual particles. */
    | "particle"
    /** Always returns []. Engine-managed. */
    | "sprite_visual";

  export type WorldQueryFilter = {
    /** Component name to query. */
    component: WorldQueryComponent;
    /** Optional tag filter (exact string match). */
    tag: string | null;
  };

  /** Generic entity handle returned by `world.query` when the component type is not known at compile time. */
  export type Entity = {
    id: EntityId;
    /** Entity position at query time. */
    position: Vec3;
    /** The entity's tags at query time. Empty array if untagged. */
    tags: ReadonlyArray<string>;
  };

  /** Entity handle returned by `world.query` when filtering for billboard emitter entities. */
  export type EmitterEntity = {
    id: EntityId;
    /** Emitter position at query time (from the entity's Transform). */
    position: Vec3;
    /** The entity's tags at query time. Empty array if untagged. */
    tags: ReadonlyArray<string>;
    /** Full emitter component snapshot at query time. */
    component: BillboardEmitterComponent;
  };

  /** Entity handle returned by `world.query` when filtering for light entities. */
  export type LightEntity = {
    id: EntityId;
    /** Light origin at query time. */
    position: Vec3;
    /** Whether the light is driven by the runtime dynamic-light buffer. Static lights baked from FGD entities are not; descriptor-spawned lights always are. */
    isDynamic: boolean;
    /** The entity's tags at query time. Empty array if untagged. */
    tags: ReadonlyArray<string>;
    /** Full component snapshot at query time. */
    component: LightComponent;
  };

  /** Returns true if the entity id refers to a live entity. */
  export function entityExists(id: EntityId): boolean;

  /** Reads a per-placement KVP value authored on the source `.map` entity. Returns null when the key is absent or the entity has no KVP bag (e.g. runtime-spawned). Available in definition and data contexts. */
  export function getEntityProperty(id: EntityId, key: string): string | null;

  /** Overwrite the LightComponent.animation on the given entity. Pass null/nil to clear. Non-unit direction samples are silently normalized; zero-length direction samples and empty channel arrays error with InvalidArgument. Definition context. */
  export function setLightAnimation(id: EntityId, animation: LightAnimation | null): void;

  /** Read the current value of an engine-global state slot by stable dotted name. Available in definition and data contexts. */
  export function storeRead(name: string): unknown;

  /** Write an engine-global state slot by stable dotted name. The value must exactly match the declared slot type. Finite numbers are clamped to the declared inclusive range. Readonly slots reject script writes with a warning and remain unchanged. Available in definition and data contexts. */
  export function storeWrite(name: string, value: unknown): void;

  /** Return the current world gravity in m/s² (negative = downward; positive = upward). Seeded from the worldspawn `initialGravity` KVP at level load and persists until the next level load or a `worldSetGravity` call. The `world.ts` vocabulary module wraps this as `world.getGravity`. */
  export function worldGetGravity(): number;

  /** Return an array of entity handles matching the filter. Available in definition and data contexts. Filter shape: { component: "light" | "transform" | "emitter" | "fog_volume" | "particle" | "sprite_visual", tag?: string }. `"particle"` and `"sprite_visual"` always return `[]` (engine-managed; scripts never iterate individual particles). Unknown component values raise InvalidArgument. The `world.ts` vocabulary module wraps this as `world.query`. */
  export function worldQuery<T extends WorldQueryComponent>(filter: { component: T; tag?: string | null }): ReadonlyArray<EntityForComponent<T>>;

  /** Set the world gravity in m/s² (negative = downward; positive = upward). NaN and non-finite values are silently ignored (a warning is logged) so a misbehaving script cannot wedge particle physics. Effect is immediate and persists until the next level load or another `worldSetGravity` call. The `world.ts` vocabulary module wraps this as `world.setGravity`. */
  export function worldSetGravity(value: number): void;
  /** Generated engine-owned state reference tree returned by `getGameState()`. */
  export type GameStateRefs = {
    readonly input: {
      readonly mode: ReadonlyStateRef<"pointer" | "focus">;
    };
    readonly player: {
      readonly health: ReadonlyStateRef<number>;
      readonly maxHealth: ReadonlyStateRef<number>;
    };
    readonly screen: {
      readonly flash: ReadonlyStateRef<ReadonlyArray<number>>;
      readonly shake: ReadonlyStateRef<ReadonlyArray<number>>;
      readonly vignette: ReadonlyStateRef<ReadonlyArray<number>>;
    };
    readonly ui: {
      readonly textEntry: WritableStateRef<string>;
    };
  };

  /** Return immutable engine-state reference descriptors. Pure; no live state read. */
  export function getGameState(): GameStateRefs;


  // -------------------------------------------------------------------------
  // SDK library — globals installed by the runtime prelude. Import by bare specifier; the bundler strips the import at compile time.

  /** Capability for entities with a scalar animation channel (brightness, density, etc.). `Channel` is type-level documentation — the handle's implementation closure knows which descriptor channel to drive. */
  export interface AnimatableScalar<Channel extends string> {
    /** Sine pulse oscillating between `min` and `max` over `periodMs`. Loops forever. */
    pulse(opts: { min: number; max: number; periodMs: number }): SequenceStep[];
    /** One-shot linear ramp from `from` to `to` over `periodMs`. Plays exactly once. */
    fade(opts: { from: number; to: number; periodMs: number }): SequenceStep[];
    /** Irregular flicker between `min` and `max` at `rate` Hz. Loops forever. */
    flicker(opts: { min: number; max: number; rate: number }): SequenceStep[];
    readonly __channel?: Channel;
  }

  /** Capability for entities with a vec3 animation channel. */
  export interface AnimatableVec3<Channel extends string> {
    /** Uniform cycle through the given vectors over `periodMs`. */
    cycle(opts: { values: Vec3[]; periodMs: number }): SequenceStep[];
    readonly __channel?: Channel;
  }

  /** Typed light handle returned by `world.query({ component: "light" })`. Composes the brightness scalar capability with vec3 channels declared directly (TypeScript collapses duplicate method names, so secondary vec3 channels are not pulled in via `AnimatableVec3` extension). */
  export interface LightEntityHandle extends LightEntity, AnimatableScalar<"brightness"> {
    /** Cycle through RGB colors over `periodMs`. Dynamic lights only. */
    colorShift(opts: { values: Vec3[]; periodMs: number }): SequenceStep[];
    /** Sweep the `direction` channel through unit vectors over `periodMs`. */
    sweep(opts: { values: Vec3[]; periodMs: number }): SequenceStep[];
  }

  /** Typed fog-volume handle returned by `world.query({ component: "fog_volume" })`. Composes the density scalar capability with secondary saturation methods declared directly. */
  export interface FogVolumeHandle extends FogVolumeEntity, AnimatableScalar<"density"> {
    /** Looping sine pulse on the `saturation` channel. */
    pulseSaturation(opts: { min: number; max: number; periodMs: number }): SequenceStep[];
    /** One-shot linear ramp on the `saturation` channel. */
    fadeSaturation(opts: { from: number; to: number; periodMs: number }): SequenceStep[];
  }

  /** Maps a component-name literal to the rich entity handle type. `"light"`
   * yields `LightEntityHandle` (capability methods); `"emitter"` yields
   * `EmitterEntity` (id, position, tags, plus the full `BillboardEmitterComponent`
   * snapshot under `component`); `"fog_volume"` yields `FogVolumeHandle`.
   * Other component names fall back to the bare `Entity` shape (`id`,
   * `position`, `tags`). */
  export type EntityForComponent<T extends WorldQueryComponent> =
    T extends "light" ? LightEntityHandle :
    T extends "emitter" ? EmitterEntity :
    T extends "fog_volume" ? FogVolumeHandle :
    Entity;

  /** Vocabulary object installed as `globalThis.world`. */
  export interface World {
    query<T extends WorldQueryComponent>(filter: {
      component: T;
      tag?: string | null;
    }): EntityForComponent<T>[];
    /** Current world gravity in m/s² (negative = downward; positive = upward). Seeded from the worldspawn `initialGravity` KVP at level load and persists until the next level load or `setGravity` call. */
    getGravity(): number;
    /** Set world gravity in m/s² (negative = downward; positive = upward). NaN and non-finite values are silently ignored with a warning logged. Effect is immediate and persists until the next level load or another `setGravity` call. */
    setGravity(value: number): void;
  }

  /** `world` vocabulary global. Wraps `worldQuery` with a typed handle. */
  export const world: World;

  /** Per-channel keyframe accepted by `timeline` / `sequence`. */
  export type Keyframe<T extends number[]> = [number, ...T];

  /** Validate `[absolute_ms, ...value]` keyframes; pass-through on success. */
  export function timeline<T extends number[]>(
    keyframes: [number, ...T][],
  ): [number, ...T][];

  /** Convert `[delta_ms, ...value]` keyframes to absolute-time form. */
  export function sequence<T extends number[]>(
    keyframes: [number, ...T][],
  ): [number, ...T][];

  // -------------------------------------------------------------------------
  // Data script vocabulary — pure descriptor builders consumed by the engine
  // when `setupLevel` returns. See: context/lib/scripting.md §2.

  /** Progress-subscription reaction body: fires `fire` when entities tagged `tag` cross kill ratio `at` (0.0–1.0). */
  export type ProgressReactionDescriptor = {
    progress: { tag: string; at: number; fire: string };
  };

  /** Primitive reaction body: invokes the named Rust primitive. With `tag`, it targets entities carrying that tag and mutates them. Without `tag`, it is a system reaction (no entities) that enqueues a typed engine command — `playSound`, `rumble`, `flashScreen`, the UI-stack reactions. `args` carries the primitive's typed payload (e.g. `{ rate: 0 }` for `setEmitterRate`, `{ sound: "alarm" }` for `playSound`). */
  export type PrimitiveReactionDescriptor = {
    primitive: string;
    tag?: string;
    args?: Record<string, unknown>;
    onComplete?: string;
  };

  /** One step in a `sequence` reaction body: invokes the named sequenced primitive against the given entity with `args`. Sequence steps target a single `EntityId`; tag-targeted primitives belong on the `Primitive` reaction path. */
  export type SetLightAnimationStep = {
    id: EntityId;
    primitive: "setLightAnimation";
    args: LightAnimation;
  };

  /** Sequence step targeting a single fog volume's `density`. Use directly for a one-shot density change. */
  export type SetFogDensityStep = {
    id: EntityId;
    primitive: "setFogDensity";
    args: { density: number };
  };

  /** Sequence step targeting a single fog volume's `glow`. */
  export type SetFogGlowStep = {
    id: EntityId;
    primitive: "setFogGlow";
    args: { glow: number };
  };

  /** Sequence step targeting a single fog volume's `edgeSoftness`. */
  export type SetFogEdgeSoftnessStep = {
    id: EntityId;
    primitive: "setFogEdgeSoftness";
    args: { edgeSoftness: number };
  };

  /** Sequence step targeting a single fog volume's `falloff`. */
  export type SetFogFalloffStep = {
    id: EntityId;
    primitive: "setFogFalloff";
    args: { falloff: number };
  };

  /** Sequence step that updates any subset of `{density, glow, edgeSoftness, falloff, tint, saturation, minBrightness, lightRange}` on a single fog volume in one component write. */
  export type SetFogParamsStep = {
    id: EntityId;
    primitive: "setFogParams";
    args: {
      density?: number;
      glow?: number;
      edgeSoftness?: number;
      falloff?: number;
      tint?: readonly [number, number, number];
      saturation?: number;
      minBrightness?: number;
      lightRange?: number;
    };
  };

  /** Sequence step that installs (or clears, when `args` is `null`) a dual-channel animation (density and/or saturation) on a single fog volume. Emitted by the `FogVolumeHandle` capability methods (`pulse`, `fade`, `flicker`, `pulseSaturation`, `fadeSaturation`). */
  export type SetFogAnimationStep = {
    id: EntityId;
    primitive: "setFogAnimation";
    args: FogAnimation | null;
  };

  /** Union of every supported sequence step shape. New sequenced primitives extend this union. */
  export type SequenceStep =
    | SetLightAnimationStep
    | SetFogDensityStep
    | SetFogGlowStep
    | SetFogEdgeSoftnessStep
    | SetFogFalloffStep
    | SetFogParamsStep
    | SetFogAnimationStep;

  /** Sequence reaction body: ordered per-entity primitive invocations. Steps run in array order at dispatch. */
  export type SequenceReactionDescriptor = {
    sequence: SequenceStep[];
  };

  /** Descriptor produced by `defineReaction`. The `name` field is merged into the descriptor at the top level so the Rust deserializer reads both fields from one flat object. */
  export type NamedReactionDescriptor = { name: string; levels?: string[] } & (
    | ProgressReactionDescriptor
    | PrimitiveReactionDescriptor
    | SequenceReactionDescriptor
  );

  /** Crossing condition: fires when the watched slot crosses the threshold in one direction. Exactly one of `below`/`above` is given. `max` is the denominator the threshold is a fraction of; omit it for a raw-value comparison (`max` defaults to `1.0`). */
  export type CrossingCondition =
    | { below: number; above?: never; max?: number }
    | { above: number; below?: never; max?: number };

  /** A state-crossing watcher entry as it appears in `setupLevel().crossings` or `ModManifest.crossings`. The condition fields are flattened in beside `slot` and `fire`; `fire` lists the named reactions dispatched when the crossing occurs. `levels` scopes mod-global crossings by map-catalog tags; omit it for every level. */
  export type CrossingDescriptor = {
    slot: string;
    max?: number;
    fire: string[];
    levels?: string[];
  } & ({ below: number } | { above: number });

  /** Bundle returned from `setupLevel`. The engine deserializes this shape in one pass at level load. */
  export type LevelManifest = {
    reactions: NamedReactionDescriptor[];
    crossings?: CrossingDescriptor[];
    /** Per-level UI trees (name + `AnchoredTree` + `alwaysOn`). Optional; same shape as `ModManifest.uiTrees` but level-scoped (cleared on unload). Malformed entries are logged and skipped. */
    uiTrees?: ReadonlyArray<ModUiTree>;
  };

  /** Build a named reaction descriptor. Pure: returns a plain object, no FFI.
   * `descriptor` accepts exactly one body shape: `progress` (kill-ratio trigger),
   * `primitive` (named Rust primitive with optional entity `tag` and typed
   * `args`), or `sequence` (ordered per-entity steps). `name` is optional; when
   * omitted a deterministic, run-stable id is derived from the body. Use explicit
   * names when TS and Luau scripts must agree. The returned handle can be passed
   * to `Button.onPress` or crossing `fire` entries.
   * @param name Stable event/reaction name consumed by dispatch. Optional.
   * @param descriptor Reaction body data consumed later by Rust. */
  export function defineReaction(
    descriptor:
      | ProgressReactionDescriptor
      | PrimitiveReactionDescriptor
      | SequenceReactionDescriptor,
  ): NamedReactionDescriptor;
  export function defineReaction(
    name: string,
    descriptor:
      | ProgressReactionDescriptor
      | PrimitiveReactionDescriptor
      | SequenceReactionDescriptor,
  ): NamedReactionDescriptor;

  /** Stamp a shared map-tag scope onto each reaction in a plain list. `tags` are matched against `ModMapEntry.tags`; omit scoping for every level. */
  export function scopeReactions(
    tags: string[],
    list: NamedReactionDescriptor[],
  ): NamedReactionDescriptor[];

  // -------------------------------------------------------------------------
  // State-store declarations. `defineStore` is special-cased in the typedef
  // generator (mirroring `worldQuery`): per-slot value types live only in the
  // runtime `schema` argument, absent at typedef emission, so the typed state
  // reference map is supplied by this hand-written generic instead of registry
  // emission.

  declare const stateRefValueBrand: unique symbol;
  declare const writableStateRefBrand: unique symbol;
  export type ScalarStateValue = number | boolean | string;
  export type NumericArrayStateValue = ReadonlyArray<number>;
  export type ReadonlyStateRef<T> = { readonly slot: string; readonly [stateRefValueBrand]: T };
  export type WritableStateRef<T> = ReadonlyStateRef<T> & { readonly [writableStateRefBrand]: T };

  /** One slot inside a `defineStore` schema. Every slot needs `default`. `type: "number"` accepts a finite numeric default plus optional inclusive `range: [min, max]`; `"boolean"` and `"string"` require matching defaults; `"enum"` requires non-empty `values` and a default in that list; `"array"` is a finite-number array. `persist` saves on clean exit; `readonly` blocks script writes. */
  export type StoreSlotSchema = { type: "number" | "boolean" | "string" | "enum" | "array"; readonly?: boolean } & Record<string, unknown>;

  /** Plain declaration data returned through `ModManifest.stores`. */
  export type StoreDeclaration = { namespace: string; schema: Record<string, StoreSlotSchema> };

  /** Maps one schema slot's `type` discriminant to its handle value type:
   * `{type:"number"}` → number ref, `{type:"boolean"}` →
   * boolean ref, `array` → numeric-array ref, and `string`/`enum` →
   * string ref. Slots with `readonly: true` produce `ReadonlyStateRef<T>`;
   * all other slots produce `WritableStateRef<T>`. */
  export type StoreStateRefForSlot<Slot, T> =
    Slot extends { readonly: true } ? ReadonlyStateRef<T> : WritableStateRef<T>;

  export type StateValueForSlot<Slot> =
    Slot extends { type: "number" } ? StoreStateRefForSlot<Slot, number> :
    Slot extends { type: "boolean" } ? StoreStateRefForSlot<Slot, boolean> :
    Slot extends { type: "array" } ? StoreStateRefForSlot<Slot, ReadonlyArray<number>> :
    StoreStateRefForSlot<Slot, string>;

  /** Result of a pure `defineStore` call. Return `declaration` from `ModManifest.stores`; use `state` references in descriptors. */
  export type StoreDefinition<S extends Record<string, StoreSlotSchema>> = {
    readonly declaration: StoreDeclaration;
    readonly state: { readonly [K in keyof S]: StateValueForSlot<S[K]> };
  };

  /** Build a state-store declaration. Pure: calling it performs no FFI and changes no engine state. `namespace` prefixes returned refs as `namespace.slotName`; `schema` declares slot names and validation rules. Returned declarations commit atomically only after the mod manifest succeeds. */
  export function defineStore<const S extends Record<string, StoreSlotSchema>>(
    namespace: string,
    schema: S,
  ): StoreDefinition<S>;


  // -------------------------------------------------------------------------
  // UI manifest wire types used by `ModManifest.uiTrees` / `LevelManifest.uiTrees`.
  //
  // Root `postretro` intentionally exposes only data shapes needed by manifest
  // declarations. UI authoring factories, layout helpers, state helpers,
  // reactions, and theme helpers are excluded from this root module; they live
  // behind the `postretro/ui` surface. The QuickJS prelude still installs
  // UI globals from `sdk/lib/prelude.ts` as temporary implementation plumbing
  // while import stripping lacks alias rewriting.

  /** The flat `kind`-tagged descriptor retained by Rust after setup. */
  export type WidgetDescriptor = { kind: string; [field: string]: unknown };
  /** Accessibility role override carried on widget and tree descriptors. */
  export type WidgetRole = "tab" | "tablist" | "checkbox" | "radio" | "listitem" | "button" | "slider" | "progressbar" | "image" | "group" | "none";
  /** Tree viewport anchor. */
  export type WidgetAnchor = "topLeft" | "top" | "topRight" | "left" | "center" | "right" | "bottomLeft" | "bottom" | "bottomRight";
  /** Tree input behavior. */
  export type WidgetCaptureMode = "capture" | "passthrough";
  /** Flat `AnchoredTree` manifest envelope stored in UI registries. */
  export type AnchoredTreeDescriptor = {
    anchor: WidgetAnchor;
    offset: [number, number];
    root: WidgetDescriptor;
    captureMode?: WidgetCaptureMode;
    initialFocus?: string;
    textEntryTarget?: string;
    accessibleName?: string;
    role?: WidgetRole;
  };
  /** Pure identity builder for entity-type descriptors. Returned from `ModManifest.entities`; `descriptor` is the full archetype object: optional `canonicalName`, optional `defaultWeapon`, and optional component presets. */
  export function defineEntity(descriptor: EntityTypeDescriptor): EntityTypeDescriptor;
  /** Pure identity builder for the mod manifest consumed from the default export. `config.name` is required; optional arrays include `entities`, `maps`, `uiTrees`, `reactions`, `crossings`, and `stores`. */
  export function defineMod(config: ModManifest): ModManifest;
  /** Pure identity builder for a mod map catalog. Entries require `id`, `path`, and `name`; optional `tags` default to empty and drive filtering plus `levels` selectors. */
  export function defineMapCatalog(entries: ModMapEntry[]): ModMapEntry[];

  // -------------------------------------------------------------------------
  // Runtime-value vocabulary — the typed command buffer (scripting.md §11). The
  // `runtime.*` builders assemble these node objects as plain data; constructing
  // a node has no FFI side effect. The union below is the *closure* of the
  // vocabulary: an author cannot name an op outside it. Field names match the
  // Rust `IrNode` wire format byte-for-byte (`a`/`b`, `x`/`lo`/`hi`, `cond`,
  // `name`, `value`) so builder output deserializes straight into `IrNode`.
  // (Author surface is `runtime`/`RuntimeValue`; the Rust substrate and wire
  // op tags keep the `ir` names — scripting.md §11, "Author-facing naming".)
  // Source of truth: crates/postretro/src/scripting/ir/mod.rs + sdk/lib/runtime.ts.
  // Static block (not registry-emitted): `register_tagged_union` /
  // `TypeShape::TaggedUnion` renders one payload *type name* per variant under
  // a fixed tag key — it cannot express per-variant inline struct fields (e.g.
  // `value`, `a`/`b`, `cond`) or the recursive `RuntimeValue` self-reference
  // that every non-leaf variant requires.

  /** Literal scalar leaf: `{ op: "const", value }`. `value` is a number or boolean. */
  export type RuntimeConst = { op: "const"; value: number | boolean };
  /** Named-input leaf: `{ op: "input", name }`. Bound to live state by the Rust evaluator. */
  export type RuntimeRead = { op: "input"; name: string };
  /** Addition: `a + b` (number). */
  export type RuntimeAdd = { op: "add"; a: RuntimeValue; b: RuntimeValue };
  /** Subtraction: `a - b` (number). */
  export type RuntimeSub = { op: "sub"; a: RuntimeValue; b: RuntimeValue };
  /** Multiplication: `a * b` (number). */
  export type RuntimeMul = { op: "mul"; a: RuntimeValue; b: RuntimeValue };
  /** Division: `a / b` (number). */
  export type RuntimeDiv = { op: "div"; a: RuntimeValue; b: RuntimeValue };
  /** Clamp `x` to `[lo, hi]` (number). */
  export type RuntimeClamp = { op: "clamp"; x: RuntimeValue; lo: RuntimeValue; hi: RuntimeValue };
  /** Linear interpolation between `a` and `b` by `t` (number). */
  export type RuntimeLerp = { op: "lerp"; a: RuntimeValue; b: RuntimeValue; t: RuntimeValue };
  /** Less-than comparison (boolean). */
  export type RuntimeLt = { op: "lt"; a: RuntimeValue; b: RuntimeValue };
  /** Less-than-or-equal comparison (boolean). */
  export type RuntimeLe = { op: "le"; a: RuntimeValue; b: RuntimeValue };
  /** Greater-than comparison (boolean). */
  export type RuntimeGt = { op: "gt"; a: RuntimeValue; b: RuntimeValue };
  /** Greater-than-or-equal comparison (boolean). */
  export type RuntimeGe = { op: "ge"; a: RuntimeValue; b: RuntimeValue };
  /** Equality comparison (boolean). */
  export type RuntimeEq = { op: "eq"; a: RuntimeValue; b: RuntimeValue };
  /** Inequality comparison (boolean). */
  export type RuntimeNe = { op: "ne"; a: RuntimeValue; b: RuntimeValue };
  /** Branchless select: `cond ? a : b`. `a` and `b` share a type. */
  export type RuntimeSelect = { op: "select"; cond: RuntimeValue; a: RuntimeValue; b: RuntimeValue };

  /** A node in the authored runtime-value tree. Closed vocabulary: every node
   * the evaluator accepts is one of these variants. New opcodes extend this
   * union in lockstep with the Rust `IrNode` enum. */
  export type RuntimeValue =
    | RuntimeConst
    | RuntimeRead
    | RuntimeAdd
    | RuntimeSub
    | RuntimeMul
    | RuntimeDiv
    | RuntimeClamp
    | RuntimeLerp
    | RuntimeLt
    | RuntimeLe
    | RuntimeGt
    | RuntimeGe
    | RuntimeEq
    | RuntimeNe
    | RuntimeSelect;

  /** A builder operand: an already-built node, or a bare `number`/`boolean`
   * literal that the builder auto-wraps into a `const` node. */
  type RuntimeOperand = RuntimeValue | number | boolean;

  /** Pure builder vocabulary for runtime values, installed as
   * `globalThis.runtime`. Every method returns a plain `RuntimeValue` object;
   * constructing a node has no FFI side effect. Bare `number`/`boolean`
   * operands are auto-wrapped into `const` nodes. Import via
   * `import { runtime } from "postretro"`. */
  export interface Runtime {
    /** Literal scalar leaf. `const` is reserved, so the builder is `constant`. */
    constant(value: number | boolean): RuntimeConst;
    /** Named-input leaf, bound to live state by name in the Rust evaluator. */
    read(name: string): RuntimeRead;
    /** `a + b` (number). */
    add(a: RuntimeOperand, b: RuntimeOperand): RuntimeAdd;
    /** `a - b` (number). */
    sub(a: RuntimeOperand, b: RuntimeOperand): RuntimeSub;
    /** `a * b` (number). */
    mul(a: RuntimeOperand, b: RuntimeOperand): RuntimeMul;
    /** `a / b` (number). */
    div(a: RuntimeOperand, b: RuntimeOperand): RuntimeDiv;
    /** Clamp `x` to `[lo, hi]` (number). */
    clamp(x: RuntimeOperand, lo: RuntimeOperand, hi: RuntimeOperand): RuntimeClamp;
    /** Linear interpolation between `a` and `b` by `t` (number). */
    lerp(a: RuntimeOperand, b: RuntimeOperand, t: RuntimeOperand): RuntimeLerp;
    /** `a < b` (boolean). */
    lt(a: RuntimeOperand, b: RuntimeOperand): RuntimeLt;
    /** `a <= b` (boolean). */
    le(a: RuntimeOperand, b: RuntimeOperand): RuntimeLe;
    /** `a > b` (boolean). */
    gt(a: RuntimeOperand, b: RuntimeOperand): RuntimeGt;
    /** `a >= b` (boolean). */
    ge(a: RuntimeOperand, b: RuntimeOperand): RuntimeGe;
    /** `a == b` (boolean). */
    eq(a: RuntimeOperand, b: RuntimeOperand): RuntimeEq;
    /** `a != b` (boolean). */
    ne(a: RuntimeOperand, b: RuntimeOperand): RuntimeNe;
    /** Branchless select: `cond ? a : b`. `a` and `b` share a type. */
    select(cond: RuntimeOperand, a: RuntimeOperand, b: RuntimeOperand): RuntimeSelect;
  }

  /** Runtime-value builder vocabulary global. */
  export const runtime: Runtime;

  // -------------------------------------------------------------------------
  // UI navigation intents — the closed gamepad-first nav vocabulary the input
  // stage produces (keyboard arrows/enter/escape, D-pad, stick edges) and that
  // UI authors reference in `capturesNav` and focus policy. Wire names mirror
  // the Rust `NavIntent` enum (input/ui_nav.rs). Template-literal-typed so a
  // typo in a `"nav.*"` string is a compile error.
  // See: context/research/ui-layer.md §16.

  /** The bare nav-intent names without the `nav.` prefix. */
  export type NavIntentName =
    | "up" | "down" | "left" | "right"
    | "next" | "prev"
    | "confirm" | "cancel"
    | "menu" | "options";

  /** A UI navigation intent wire name. Template-literal type over the closed
   * `NavIntentName` set, so only `"nav.up"` … `"nav.options"` type-check. */
  export type NavIntent = `nav.${NavIntentName}`;
}


declare module "postretro/ui" {
  import type {
    ReadonlyStateRef,
    WritableStateRef,
    ScalarStateValue,
    NumericArrayStateValue,
    GameStateRefs,
    ModUiTree,
    PrimitiveReactionDescriptor,
    NamedReactionDescriptor,
    CrossingCondition,
    CrossingDescriptor,
  } from "postretro";

  /** Linear RGBA color token value. Components are in display-linear 0-1 space; alpha is the fourth element. */
  export type ThemeColorValue = readonly [number, number, number, number];
  declare const themeTokenBrand: unique symbol;
  /** Runtime-authenticated SDK token record. Widget factories unwrap only records produced by `getDesignTokens(theme)`, not hand-built lookalikes. */
  export type ThemeToken<Category extends "color" | "font" | "spacing"> = Readonly<{
    __postretroToken: Category;
    token: string;
    readonly [themeTokenBrand]: Category;
  }>;
  export type ColorToken = ThemeToken<"color">;
  export type FontToken = ThemeToken<"font">;
  export type SpacingToken = ThemeToken<"spacing">;
  export type ThemeTokenTree<Leaf> = { readonly [key: string]: Leaf | ThemeTokenTree<Leaf> };
  /** Nested singular token groups accepted by `defineTheme`. */
  export type ThemeDefinition = {
    readonly color?: ThemeTokenTree<ThemeColorValue>;
    readonly font?: ThemeTokenTree<string>;
    readonly spacing?: ThemeTokenTree<number>;
    readonly colors?: never;
    readonly fonts?: never;
    readonly tokens?: never;
  };
  export type JoinThemePath<Prefix extends string, Key extends string> = Prefix extends "" ? Key : `${Prefix}.${Key}`;
  export type FlattenTokenKeys<Tree, Leaf, Prefix extends string = ""> = Tree extends Leaf
    ? Prefix
    : Tree extends Readonly<Record<string, unknown>>
      ? { [K in Extract<keyof Tree, string>]: FlattenTokenKeys<Tree[K], Leaf, JoinThemePath<Prefix, K>> }[Extract<keyof Tree, string>]
      : never;
  export type FlatTokenMap<Tree, Leaf, Value> = Record<FlattenTokenKeys<NonNullable<Tree>, Leaf>, Value>;
  export type DesignTokenTree<Tree, Leaf, Token, Prefix extends string = ""> = Tree extends Leaf
    ? Token
    : Tree extends Readonly<Record<string, unknown>>
      ? { readonly [K in Extract<keyof Tree, string>]: DesignTokenTree<Tree[K], Leaf, Token, JoinThemePath<Prefix, K>> }
      : never;
  export type DesignTokenGroup<Tree, Leaf, Token> = [Tree] extends [undefined] ? {} : DesignTokenTree<NonNullable<Tree>, Leaf, Token>;
  export type DesignTokens<T extends ThemeDefinition> = {
    readonly color: DesignTokenGroup<T["color"], ThemeColorValue, ColorToken>;
    readonly font: DesignTokenGroup<T["font"], string, FontToken>;
    readonly spacing: DesignTokenGroup<T["spacing"], number, SpacingToken>;
  };
  declare const definedThemeBrand: unique symbol;
  /** Manifest-compatible flat theme maps returned from `defineTheme`. */
  export type DefinedTheme<T extends ThemeDefinition> = {
    readonly colors: FlatTokenMap<T["color"], ThemeColorValue, ThemeColorValue>;
    readonly fonts: FlatTokenMap<T["font"], string, string>;
    readonly spacing: FlatTokenMap<T["spacing"], number, number>;
    readonly [definedThemeBrand]: T;
  };
  export function defineTheme<const T extends ThemeDefinition>(theme: T): DefinedTheme<T>;
  export function getDesignTokens<const T extends ThemeDefinition>(theme: DefinedTheme<T>): DesignTokens<T>;

  export type LocalizedText = string;
  export type WidgetColor = [number, number, number, number] | ColorToken;
  export type WidgetSpacing = number | SpacingToken;
  export type WidgetAlign = "start" | "center" | "end" | "stretch";
  export type WidgetEasing = "linear" | "easeIn" | "easeOut" | "easeInOut";
  export type NumberTween = { durationMs: number; easing: WidgetEasing; from?: number };
  export type ColorTween = { durationMs: number; easing: WidgetEasing; from?: [number, number, number, number] };
  export type LocalBindRef = { local: string };
  export type PredicateValue = number | boolean | string;
  export type Predicate = ((ReadonlyStateRef<PredicateValue> & { local?: never }) | LocalBindRef) & { equals?: PredicateValue };
  export type WidgetRole = "tab" | "tablist" | "checkbox" | "radio" | "listitem" | "button" | "slider" | "progressbar" | "image" | "group" | "none";
  export type AnnouncePriority = "polite" | "assertive";
  export type TextBindProp = ((ReadonlyStateRef<ScalarStateValue> & { local?: never }) | LocalBindRef) & { format?: string; tween?: NumberTween };
  export type PanelBindProp = ((ReadonlyStateRef<NumericArrayStateValue> & { local?: never; format?: never }) | LocalBindRef) & { tween?: ColorTween };
  export type SliderBindProp = ((WritableStateRef<number> & { local?: never; format?: never }) | LocalBindRef) & { tween?: NumberTween };
  export type BarBindProp = ((ReadonlyStateRef<number> & { local?: never; format?: never }) | LocalBindRef) & { tween?: NumberTween };
  export type BarMaxProp = number | ReadonlyStateRef<number>;
  export type StyleRangeEntry = { upTo?: number; color?: WidgetColor; pulse?: { periodMs: number }; flash?: { durationMs: number } };
  export type StyleRangesProp = { max: number; entries: StyleRangeEntry[] };
  export type BorderProp = { texture: string; slice: [number, number, number, number]; tint: WidgetColor };
  export type FocusNeighborsProp = { up?: string; down?: string; left?: string; right?: string };
  export type RepeatPolicyProp = { initialDelayMs: number; intervalMs: number };
  export type ReactionHandleRef = { name: string };
  export type WidgetDescriptor = { kind: string; [field: string]: unknown };

  /** Props for `Text`. `content` is the fallback/display string; `fontSize` is a finite logical-px number defaulting to 12; `color` is an RGBA tuple or color token defaulting to white. `bind` may replace rendered content from state; `styleRanges` recolors by normalized value. */
  export type TextProps = { content: LocalizedText; fontSize?: number; color?: WidgetColor; font?: FontToken; bind?: TextBindProp; styleRanges?: StyleRangesProp; id?: string; focusNeighbors?: FocusNeighborsProp; visibleWhen?: Predicate; role?: WidgetRole };
  /** Build a `text` widget descriptor. Pure: returns data retained by Rust after manifest/setup load. */
  export function Text(props: TextProps): WidgetDescriptor;
  /** Props for `Panel`. `fill` is required RGBA/token color; `border` is optional 9-slice data; `bind` may replace fill from a numeric RGBA state value. */
  export type PanelProps = { fill: WidgetColor; border?: BorderProp; bind?: PanelBindProp; styleRanges?: StyleRangesProp; id?: string; focusNeighbors?: FocusNeighborsProp; visibleWhen?: Predicate; role?: WidgetRole };
  /** Build a solid panel widget descriptor. Pure; no engine side effect. */
  export function Panel(props: PanelProps): WidgetDescriptor;
  /** Props for `Image`. `asset` is a UI texture key. Exactly one accessible-name path is required: `label` for meaningful images or `decorative: true` for ignored imagery. */
  export type ImageProps = { asset: string; id?: string; focusNeighbors?: FocusNeighborsProp; visibleWhen?: Predicate; role?: WidgetRole } & ({ label: string; decorative?: never } | { decorative: true; label?: never });
  /** Build an image widget descriptor sized from the texture asset's natural dimensions. */
  export function Image(props: ImageProps): WidgetDescriptor;
  /** Props for `Spacer`. `flexGrow` is a finite proportional share of leftover space; defaults to 1. */
  export type SpacerProps = { flexGrow?: number; id?: string; visibleWhen?: Predicate; role?: WidgetRole };
  /** Build a spacer widget descriptor. */
  export function Spacer(props?: SpacerProps): WidgetDescriptor;
  /** Props for `Button`. `id` is required for focus/activation. `onPress` accepts a `defineReaction` handle, bare reaction name, or reserved `ui.*` action. Exactly one of `label` or `labelledBy` is required. */
  export type ButtonProps = { id: string; onPress: ReactionHandleRef | string; repeatOnHold?: RepeatPolicyProp; focusNeighbors?: FocusNeighborsProp; selected?: Predicate; checked?: Predicate; bind?: Predicate; styleRanges?: StyleRangesProp; disabled?: boolean; visibleWhen?: Predicate; role?: WidgetRole } & ({ label: LocalizedText; labelledBy?: never } | { labelledBy: string; label?: never });
  /** Build an interactive button descriptor. Pure; activation is resolved by the app at runtime. */
  export function Button(props: ButtonProps): WidgetDescriptor;
  /** Props for `Slider`. `bind` must be writable numeric state/local cell. `min`, `max`, and `step` are finite numbers; navigation clamps writes into `[min, max]`. Exactly one of `label` or `labelledBy` is required. */
  export type SliderProps = { id: string; bind: SliderBindProp; min: number; max: number; step: number; capturesNav?: string[]; focusNeighbors?: FocusNeighborsProp; disabled?: boolean; visibleWhen?: Predicate; role?: WidgetRole } & ({ label: LocalizedText; labelledBy?: never } | { labelledBy: string; label?: never });
  /** Build an interactive slider descriptor. */
  export function Slider(props: SliderProps): WidgetDescriptor;
  /** Props for `Bar`. `bind` is readonly numeric state/local value; `max` is a finite number or readonly numeric state ref; `fill` and `background` are RGBA/token colors. */
  export type BarProps = { bind: BarBindProp; max: BarMaxProp; fill: WidgetColor; background: WidgetColor; styleRanges?: StyleRangesProp; id?: string; visibleWhen?: Predicate; role?: WidgetRole };
  /** Build a passive bar descriptor. Displayed fill is `value / max` clamped to `[0, 1]`. */
  export function Bar(props: BarProps): WidgetDescriptor;
  /** Props for `Announce`. `priority` defaults to `"polite"`; `visibleWhen` gates whether the live-region message is active. */
  export type AnnounceProps = { priority?: AnnouncePriority; visibleWhen?: Predicate };
  /** Build a non-visual live-region announcement. `text` is positional display text. */
  export function Announce(props: AnnounceProps, text: LocalizedText): WidgetDescriptor;

  export type FocusKind = "linear" | "spatial";
  export type FocusPolicyProp = FocusKind | { policy: FocusKind; wrap?: boolean; repeat?: RepeatPolicyProp };
  /** Props for `VStack`/`HStack`. `gap`/`padding` default to 0, `align` defaults to `"start"`, and optional `localState` declares presentation-only cells scoped to this container. */
  export type StackProps = { gap?: WidgetSpacing; padding?: WidgetSpacing; align?: WidgetAlign; id?: string; focusNeighbors?: FocusNeighborsProp; focus?: FocusPolicyProp; restoreOnReturn?: boolean; fill?: WidgetColor; border?: BorderProp; localState?: { scope: string; cells: Record<string, CellInit> }; visibleWhen?: Predicate; role?: WidgetRole };
  /** Props for `Grid`. `cols` is required and must be an integer >= 1; children flow row-major. */
  export type GridProps = { gap?: WidgetSpacing; padding?: WidgetSpacing; align?: WidgetAlign; id?: string; focusNeighbors?: FocusNeighborsProp; focus?: FocusPolicyProp; restoreOnReturn?: boolean; cols: number; visibleWhen?: Predicate; role?: WidgetRole };
  /** Build a vertical stack descriptor. `children` is positional, not a prop. */
  export function VStack(props?: StackProps, children?: WidgetDescriptor[]): WidgetDescriptor;
  /** Build a horizontal stack descriptor. `children` is positional, not a prop. */
  export function HStack(props?: StackProps, children?: WidgetDescriptor[]): WidgetDescriptor;
  /** Build a grid descriptor. `children` is positional, not a prop. */
  export function Grid(props: GridProps, children?: WidgetDescriptor[]): WidgetDescriptor;

  export type WidgetAnchor = "topLeft" | "top" | "topRight" | "left" | "center" | "right" | "bottomLeft" | "bottom" | "bottomRight";
  export type WidgetCaptureMode = "capture" | "passthrough";
  /** Props for `Tree`. `anchor` and `offset` place the root in 1280x720 logical UI space. `captureMode` defaults to `"passthrough"`; `initialFocus` names a widget id; `textEntryTarget` is a writable string state ref. */
  export type TreeProps = { anchor: WidgetAnchor; offset: [number, number]; captureMode?: WidgetCaptureMode; initialFocus?: string; textEntryTarget?: WritableStateRef<string>; accessibleName?: string; role?: WidgetRole };
  export type AnchoredTreeDescriptor = { anchor: WidgetAnchor; offset: [number, number]; root: WidgetDescriptor; captureMode?: WidgetCaptureMode; initialFocus?: string; textEntryTarget?: string; accessibleName?: string; role?: WidgetRole };
  /** Wrap a root widget in an anchored tree placement envelope. Pure; registration happens through `defineUiTree` and manifest data. */
  export function Tree(props: TreeProps, root: WidgetDescriptor): AnchoredTreeDescriptor;
  /** Props accepted by `defineUiTree`. `name` is the registry key; `tree` is from `Tree`; `alwaysOn` renders as a base layer such as HUD. */
  export type UiTreeRegistrationProps<Name extends string = string> = { name: Name; tree: AnchoredTreeDescriptor; alwaysOn?: boolean };
  export type UiTreeRegistration<Name extends string = string> = ModUiTree & { readonly name: Name };
  /** Build a UI-tree registration object. Pure; include the result in `ModManifest.uiTrees` or `setupLevel().uiTrees` to register it. */
  export function defineUiTree<const Name extends string>(registration: UiTreeRegistrationProps<Name>): UiTreeRegistration<Name>;

  export type StateBindOptionsFor<T> =
    T extends number ? { format?: string; tween?: NumberTween; slot?: never; local?: never } :
    T extends NumericArrayStateValue ? { tween?: ColorTween; slot?: never; local?: never } :
    T extends ScalarStateValue ? { format?: string; slot?: never; local?: never } :
    never;
  /** Compose bind-only options onto a state ref. Pure; it emits `{ slot, ...options }` for widget props and never reads live state. */
  export function bindState<T>(ref: ReadonlyStateRef<T>): ReadonlyStateRef<T>;
  export function bindState<T, Options extends StateBindOptionsFor<T>>(ref: ReadonlyStateRef<T>, options: Options): ReadonlyStateRef<T> & Omit<Options, "slot" | "local">;
  /** Build a scalar equality predicate for `visibleWhen`, `selected`, or `checked`. */
  export function stateEquals<T extends PredicateValue>(ref: ReadonlyStateRef<T>, value: T): Predicate;
  type CellInit = number | boolean | string | [number, number, number, number];
  export type LocalStateHandle<T extends CellInit> = { get(): LocalBindRef; set(value: T): PrimitiveReactionDescriptor; is(value: T): Predicate };
  export type LocalStateBundle<I extends Record<string, CellInit>> = { scope: { scope: string; cells: I }; cells: { [K in keyof I]: LocalStateHandle<I[K]> } };
  /** Declare presentation-local cells. `init` keys are cell names; values may be number, boolean, string, or RGBA tuple. Pure; cells live only inside the nearest container using the returned `scope`. */
  export function createLocalState<I extends Record<string, CellInit>>(init: I): LocalStateBundle<I>;
  export function Switch(cell: LocalStateHandle<string>, map: Record<string, WidgetDescriptor>): WidgetDescriptor[];
  export const ui: { createLocalState: typeof createLocalState };
  export function getGameState(): GameStateRefs;

  /** Build a state-crossing watcher for numeric refs. `condition` gives exactly one finite `below` or `above` threshold; optional `max` is a finite denominator. `fire` accepts reaction handles or names. */
  export function onStateCrossing(ref: ReadonlyStateRef<number>, condition: CrossingCondition, fire: (NamedReactionDescriptor | string)[]): CrossingDescriptor;
  /** Play `sound` on optional mixer `bus`; omitted/null bus uses the engine default. */
  export function playSound(sound: string, bus?: string | null): PrimitiveReactionDescriptor;
  /** Trigger gamepad rumble. `strong` and optional `weak` are motor intensities in [0, 1]; `durationMs` is milliseconds. */
  export function rumble(strong: number, durationMs: number, weak?: number | null): PrimitiveReactionDescriptor;
  /** Flash the screen with linear RGBA `color`; `durationMs` is the decay time in milliseconds. */
  export function flashScreen(color: [number, number, number, number], durationMs: number): PrimitiveReactionDescriptor;
  /** Apply a screen-edge vignette. `strength` is the peak amount, `durationMs` is total rise+decay time, and optional `color` is linear RGB. */
  export function vignette(strength: number, durationMs: number, color?: [number, number, number] | null): PrimitiveReactionDescriptor;
  /** Shake the screen. `amplitude` is logical-reference px, `durationMs` is milliseconds, and optional `frequency` is Hz. */
  export function screenShake(amplitude: number, durationMs: number, frequency?: number | null): PrimitiveReactionDescriptor;
  /** Push UI tree `tree` as a modal; optional `onCommit` names a reaction fired on commit. Unknown tree names warn and no-op. */
  export function showDialog(tree: string, onCommit?: string | null): PrimitiveReactionDescriptor;
  export const KEYBOARD_TREE: "keyboard";
  export const CLOSE_DIALOG_ACTION: "ui.closeDialog";
  export const EXIT_TO_DESKTOP_ACTION: "ui.exitToDesktop";
  /** Reserved `Button.onPress` action for returning to the frontend; same lifecycle path as `returnToFrontend()`. */
  export const QUIT_TO_MENU_ACTION: "ui.quitToMenu";
  /** Open the engine keyboard modal. Optional `onCommit` names a reaction fired when text entry commits. */
  export function openTextEntry(onCommit?: string | null): PrimitiveReactionDescriptor;
  /** Push a menu tree by registry name. Unknown tree names warn and no-op. */
  export function openMenu(tree: string): PrimitiveReactionDescriptor;
  /** Pop the active modal. Empty stack warns and no-ops. */
  export function closeDialog(): PrimitiveReactionDescriptor;
  /** Queue a catalog map load. `id` must match a committed `ModMapEntry.id`; unknown ids warn and no-op. */
  export function loadLevel(id: string): PrimitiveReactionDescriptor;
  /** Reload the active level from retained catalog id or raw dev path. No active level means no-op. */
  export function restartLevel(): PrimitiveReactionDescriptor;
  /** Return to the frontend menu and reload its optional backdrop level. */
  export function returnToFrontend(): PrimitiveReactionDescriptor;
  /** Write `value` to a writable state ref at game-logic time; runtime validates type/range and rejects readonly slots. */
  export function updateState<T>(ref: WritableStateRef<T>, value: T): PrimitiveReactionDescriptor;
  export function appendText(ref: WritableStateRef<string>, text: string): PrimitiveReactionDescriptor;
  export function backspaceText(ref: WritableStateRef<string>): PrimitiveReactionDescriptor;
  export function clearText(ref: WritableStateRef<string>): PrimitiveReactionDescriptor;
}
