// Generated by tools/gen_stress_map.py; do not hand-edit.
import { defineReaction, spawner, world } from "postretro";

export function setupLevel(_ctx: unknown) {
  const reactions = [
    defineReaction("warren.closet.0.spawn",
      spawner({ tag: "warren_closet_spawner_0" }).fire(),
    ),
    defineReaction("warren.closet.1.spawn",
      spawner({ tag: "warren_closet_spawner_1" }).fire(),
    ),
    defineReaction("warren.closet.2.spawn",
      spawner({ tag: "warren_closet_spawner_2" }).fire(),
    ),
  ];
  return { reactions };
}
