// Generated by tools/gen_stress_map.py; do not hand-edit.
import { defineReaction, getMapEntities } from "postretro";

export function setupLevel(_ctx: unknown) {
  const reactions = [
    defineReaction("warren.closet.0.spawn", {
      sequence: getMapEntities("spawner", { tag: "warren_closet_spawner_0" })
        .flatMap((closet) => closet.fire()),
    }),
    defineReaction("warren.closet.1.spawn", {
      sequence: getMapEntities("spawner", { tag: "warren_closet_spawner_1" })
        .flatMap((closet) => closet.fire()),
    }),
    defineReaction("warren.closet.2.spawn", {
      sequence: getMapEntities("spawner", { tag: "warren_closet_spawner_2" })
        .flatMap((closet) => closet.fire()),
    }),
  ];
  return { reactions };
}
