// QuickJS subsystem: one `rquickjs::Runtime` plus the definition context.
// See: context/lib/scripting.md
//
// Lifecycle:
//   * One `rquickjs::Runtime` per subsystem (owns GC, memory limit).
//   * Two contexts per level:
//       - `definition_ctx`: long-lived context for cross-script definition-scope
//         code. Carries DefinitionOnly/Both primitives as real functions.
//       - Ephemeral data context: a short-lived context created fresh per level
//         in `run_data_script_quickjs`. This is the correct entry point for
//         level-load data-script execution — not `definition_ctx`.
//   * `__collect_definitions` is a magic sink injected into the definition
//     context only. It is NOT a registered primitive.

use std::cell::RefCell;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::rc::Rc;

use rquickjs::{CatchResultExt, CaughtError, Context, Ctx, FromJs, Function, IntoJs, Runtime};
use serde::{Deserialize, Serialize};

use super::error::ScriptError;
use super::primitives_registry::{PrimitiveRegistry, ScriptPrimitive};

/// Default memory cap per QuickJS `Runtime`. 100 MB is a comfortable ceiling
/// for the single-level working set; tune after profiling real content.
const DEFAULT_MEMORY_LIMIT: usize = 100 * 1024 * 1024;

/// Engine-internal name for the accumulator sink installed into the definition
/// context. Leading underscore is the convention the type-definition generator
/// uses to skip engine-internal functions.
const COLLECT_FN_NAME: &str = "__collect_definitions";

/// SDK library prelude bundled at compile time. Generated by `build.rs` from
/// `sdk/lib/**/*.ts` so the vocabulary symbols (`world`, `flicker`, `pulse`,
/// …) resolve as globals in every QuickJS context.
const SDK_PRELUDE_JS: &str = include_str!(concat!(env!("OUT_DIR"), "/prelude.js"));

/// Evaluate the SDK prelude inside `ctx`. The prelude is plain script-mode JS
/// — its `globalThis.x = expr` tail leaves the symbols available to scripts
/// loaded into the same context later.
pub(crate) fn evaluate_prelude(ctx: &Ctx<'_>) -> Result<(), ScriptError> {
    super::game_state_refs::install_quickjs_bridge(ctx)?;
    ctx.eval::<(), _>(SDK_PRELUDE_JS)
        .map_err(|e| ScriptError::ScriptThrew {
            msg: format!("failed to evaluate SDK prelude: {e}"),
            source_name: "sdk/lib/prelude.js".to_string(),
        })?;
    Ok(())
}

/// Configuration for a [`QuickJsSubsystem`]. `memory_limit_bytes` defaults to
/// 100 MB; override for measured workloads.
#[derive(Clone, Copy, Debug)]
pub(crate) struct QuickJsConfig {
    pub(crate) memory_limit_bytes: usize,
}

impl Default for QuickJsConfig {
    fn default() -> Self {
        Self {
            memory_limit_bytes: DEFAULT_MEMORY_LIMIT,
        }
    }
}

/// Placeholder archetype record. Sufficient to prove the Rust/JS round-trip
/// for definition-time accumulation; a future archetype plan replaces this
/// with the real descriptor shape.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct ArchetypeDescriptor {
    pub(crate) name: String,
}

/// Shared accumulator feeding `__collect_definitions`. Definition helpers push
/// into this `Vec`; the sink drains and returns it.
///
/// `Rc<RefCell<_>>` over `Arc<Mutex<_>>`: scripting is single-threaded (see
/// `scripting::ctx`) and `RefCell` does not poison.
pub(crate) type ArchetypeAccumulator = Rc<RefCell<Vec<ArchetypeDescriptor>>>;

/// rquickjs subsystem: one `Runtime`, one definition context, and the
/// primitive registry handle used by short-lived data contexts.
pub(crate) struct QuickJsSubsystem {
    runtime: Runtime,
    definition_ctx: Context,
    /// Kept so short-lived data contexts can reinstall primitives without
    /// requiring the caller to pass the registry back in. Each `ScriptPrimitive`
    /// is `Clone` with `Arc`-backed closures — cheap shallow copy.
    primitives: Vec<ScriptPrimitive>,
    /// Shared with the `__collect_definitions` function installed into
    /// `definition_ctx`.
    archetypes: ArchetypeAccumulator,
}

impl QuickJsSubsystem {
    /// Construct a subsystem: build the runtime, set the memory limit, and
    /// create the definition context with primitives installed.
    pub(crate) fn new(
        registry: &PrimitiveRegistry,
        cfg: &QuickJsConfig,
    ) -> Result<Self, ScriptError> {
        let runtime = Runtime::new().map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
        runtime.set_memory_limit(cfg.memory_limit_bytes);

        let archetypes: ArchetypeAccumulator = Rc::new(RefCell::new(Vec::new()));

        let primitives_snapshot: Vec<ScriptPrimitive> = registry.iter().cloned().collect();
        let definition_ctx =
            build_definition_context_from_snapshot(&runtime, &primitives_snapshot, &archetypes)?;

        Ok(Self {
            runtime,
            definition_ctx,
            primitives: primitives_snapshot,
            archetypes,
        })
    }

    /// Borrow the definition context so callers can enter it via `ctx.with`.
    pub(crate) fn definition_ctx(&self) -> &Context {
        &self.definition_ctx
    }

    /// Borrow the underlying `rquickjs::Runtime`.
    pub(crate) fn runtime(&self) -> &Runtime {
        &self.runtime
    }

    /// Borrow the primitive snapshot.
    pub(crate) fn primitives(&self) -> &[ScriptPrimitive] {
        &self.primitives
    }

    /// Shared handle to the archetype accumulator. Exposed for tests and for
    /// the caller that drains it after evaluating definition scripts.
    pub(crate) fn archetypes(&self) -> &ArchetypeAccumulator {
        &self.archetypes
    }
}

/// Evaluate `source` inside `ctx`, converting JS exceptions into
/// `ScriptError::ScriptThrew` and logging at `error` level. Must be called
/// inside a `ctx.with(...)` closure. A thrown exception does not poison the
/// context — subsequent calls continue to work.
pub(crate) fn run_script<'js, T>(ctx: &Ctx<'js>, source: &str, name: &str) -> Result<T, ScriptError>
where
    T: FromJs<'js>,
{
    match ctx.eval::<T, _>(source).catch(ctx) {
        Ok(v) => Ok(v),
        Err(caught) => Err(caught_error_to_script_error(caught, name)),
    }
}

/// Convert a `CaughtError` to `ScriptError::ScriptThrew` and log it.
/// Shared by `run_script` and future helpers that call into the context.
fn caught_error_to_script_error(caught: CaughtError<'_>, source: &str) -> ScriptError {
    let msg = caught.to_string();
    log::error!(target: "script/quickjs", "script `{source}` threw: {msg}");
    ScriptError::ScriptThrew {
        msg,
        source_name: source.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Context construction helpers.

fn build_definition_context_from_snapshot(
    runtime: &Runtime,
    primitives: &[ScriptPrimitive],
    archetypes: &ArchetypeAccumulator,
) -> Result<Context, ScriptError> {
    let ctx = Context::full(runtime).map_err(|e| ScriptError::InvalidArgument {
        reason: e.to_string(),
    })?;
    let archetypes = archetypes.clone();
    ctx.with(|ctx| -> Result<(), ScriptError> {
        install_primitives(&ctx, primitives)?;
        install_collect_definitions(&ctx, archetypes)?;
        evaluate_prelude(&ctx)?;
        Ok(())
    })?;
    Ok(ctx)
}

/// Install each primitive into `ctx`.
fn install_primitives(ctx: &Ctx<'_>, primitives: &[ScriptPrimitive]) -> Result<(), ScriptError> {
    for p in primitives {
        (p.quickjs_installer)(ctx).map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
    }
    Ok(())
}

/// Install the `__collect_definitions` sink as a global function on `ctx`.
/// Signature: `() -> ArchetypeDescriptor[]`. Drains the accumulator on each
/// call so a single definition pass cannot double-report.
fn install_collect_definitions(
    ctx: &Ctx<'_>,
    archetypes: ArchetypeAccumulator,
) -> Result<(), ScriptError> {
    let globals = ctx.globals();
    // `Vec<DescriptorJs>`: rquickjs' `IntoJs` for `Vec` encodes as a JS array;
    // the closure blanket impl handles `'js` lifetime threading without explicit
    // naming (not possible for closures in stable Rust).
    let f = Function::new(
        ctx.clone(),
        move |ctx: rquickjs::Ctx<'_>| -> rquickjs::Result<Vec<DescriptorJs>> {
            let result = catch_unwind(AssertUnwindSafe(|| {
                let drained: Vec<ArchetypeDescriptor> = archetypes.borrow_mut().drain(..).collect();
                drained
                    .into_iter()
                    .map(DescriptorJs::from)
                    .collect::<Vec<_>>()
            }));
            match result {
                Ok(v) => Ok(v),
                Err(_) => {
                    let err = ScriptError::Panicked {
                        name: COLLECT_FN_NAME,
                    };
                    Err(rquickjs::Exception::from_message(ctx.clone(), &err.to_string())?.throw())
                }
            }
        },
    )
    .map_err(|e| ScriptError::InvalidArgument {
        reason: e.to_string(),
    })?;
    globals
        .set(COLLECT_FN_NAME, f)
        .map_err(|e| ScriptError::InvalidArgument {
            reason: e.to_string(),
        })?;
    Ok(())
}

/// JS-facing shape for an `ArchetypeDescriptor`. Separate from the
/// serde-serializable record so the wire encoding stays decoupled from the
/// Rust-side representation.
struct DescriptorJs {
    name: String,
}

impl From<ArchetypeDescriptor> for DescriptorJs {
    fn from(d: ArchetypeDescriptor) -> Self {
        Self { name: d.name }
    }
}

impl<'js> IntoJs<'js> for DescriptorJs {
    fn into_js(self, ctx: &Ctx<'js>) -> rquickjs::Result<rquickjs::Value<'js>> {
        let o = rquickjs::Object::new(ctx.clone())?;
        o.set("name", self.name)?;
        Ok(o.into_value())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scripting::ctx::ScriptCtx;
    use crate::scripting::primitives::register_all;
    use crate::scripting::primitives_registry::ContextScope;

    fn setup() -> (QuickJsSubsystem, ScriptCtx) {
        let ctx = ScriptCtx::new();
        let mut registry = PrimitiveRegistry::new();
        register_all(&mut registry, ctx.clone());
        let subsys = QuickJsSubsystem::new(&registry, &QuickJsConfig::default()).unwrap();
        (subsys, ctx)
    }

    #[test]
    fn new_constructs_runtime_and_definition_context() {
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let v: u32 = ctx.eval("1 + 2").unwrap();
            assert_eq!(v, 3);
        });
    }

    #[test]
    fn collect_definitions_round_trips_through_accumulator() {
        // Build a subsystem, inject a test-only `defineEntity` stub that
        // pushes a fixed descriptor, evaluate a script that calls it, then
        // have Rust call `__collect_definitions` and verify the drain.
        let (subsys, _ctx) = setup();
        let archetypes = subsys.archetypes().clone();

        subsys.definition_ctx().with(|ctx| {
            // Install test-only defineEntity stub. It closes over the same
            // accumulator as __collect_definitions.
            let accum = archetypes.clone();
            let define = Function::new(ctx.clone(), move |name: String| -> rquickjs::Result<()> {
                accum.borrow_mut().push(ArchetypeDescriptor { name });
                Ok(())
            })
            .unwrap();
            ctx.globals().set("defineEntity", define).unwrap();

            // Script pushes three archetypes.
            ctx.eval::<(), _>(
                r#"
                defineEntity("goblin");
                defineEntity("orc");
                defineEntity("troll");
                "#,
            )
            .unwrap();

            // Drain via the magic sink and assert shape.
            let names: Vec<String> = ctx
                .eval(
                    r#"
                    __collect_definitions().map(d => d.name)
                    "#,
                )
                .unwrap();
            assert_eq!(names, vec!["goblin", "orc", "troll"]);
        });

        // Accumulator must be drained after the call.
        assert!(archetypes.borrow().is_empty());
    }

    #[test]
    fn run_script_returns_script_threw_and_context_is_not_poisoned() {
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let err = run_script::<()>(&ctx, "throw new Error('boom');", "test.js")
                .expect_err("script should throw");
            match err {
                ScriptError::ScriptThrew { msg, source_name } => {
                    assert_eq!(source_name, "test.js");
                    assert!(msg.contains("boom"), "msg: {msg}");
                }
                other => panic!("expected ScriptThrew, got {other:?}"),
            }
            // Context must still be usable.
            let v: u32 = run_script::<u32>(&ctx, "1 + 1", "followup.js").unwrap();
            assert_eq!(v, 2);
        });
    }

    #[test]
    fn panicking_primitive_does_not_unwind_past_ffi_boundary() {
        // Verify through the full subsystem stack that a Rust-side panic
        // reaches the script as a catchable exception. `boom` captures no
        // `ScriptCtx`, so this test skips the usual setup().
        let mut registry = PrimitiveRegistry::new();
        registry
            .register("boom", || -> Result<u32, ScriptError> {
                panic!("intentional");
            })
            .scope(ContextScope::Both)
            .finish();
        let subsys = QuickJsSubsystem::new(&registry, &QuickJsConfig::default()).unwrap();
        subsys.definition_ctx().with(|ctx| {
            let msg: String = ctx
                .eval(
                    r#"
                    try { boom(); "no-throw" }
                    catch (e) { String(e.message || e) }
                    "#,
                )
                .unwrap();
            assert!(msg.contains("panicked"), "got: {msg}");
        });
    }

    /// JS snippet shared by the fog-handle curve tests. Monkey-patches the
    /// `worldQuery` primitive to return one synthetic fog snapshot, then runs
    /// `world.query({ component: "fog_volume" })` so the SDK's bundled
    /// `wrapFogVolumeEntity` builds the handle. The capability-handle refactor
    /// folded curve construction into handle methods (`fog.pulse({ ... })`)
    /// that are no longer reachable as bare globals — the only public entry
    /// point is `world.query`. Override pattern keeps the test self-contained
    /// without exposing wrapper internals to author scripts.
    const FOG_HANDLE_FIXTURE: &str = r#"
        const fakeSnapshot = {
            id: ID,
            position: { x: 0, y: 0, z: 0 },
            tags: [],
            component: {
                density: 1.0, glow: 0.5, edgeSoftness: 0,
                falloff: 1.0, tint: [1, 1, 1],
                saturation: 1.0, minBrightness: 0.0, lightRange: 1.0,
                animation: null,
            },
        };
        const realWorldQuery = globalThis.worldQuery;
        globalThis.worldQuery = (filter) => {
            if (filter.component === "fog_volume") return [fakeSnapshot];
            return realWorldQuery(filter);
        };
        const fogs = world.query({ component: "fog_volume" });
        globalThis.worldQuery = realWorldQuery;
        if (fogs.length !== 1) throw new Error("expected 1 fog, got " + fogs.length);
        const fog = fogs[0];
    "#;

    #[test]
    fn fog_handle_pulse_returns_single_step_set_fog_animation() {
        // `fog.pulse({ ... })` must emit exactly one `setFogAnimation` step
        // whose `args.density` is a 17-sample sine curve (16 intervals + wrap
        // sample), with `playCount = null` (loop forever). The 17th sample
        // equals the 1st so the linear sampler interpolates cleanly at the
        // period boundary. Replaces the old free-`fogPulse` test — curve
        // generation is now a handle method.
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let src = FOG_HANDLE_FIXTURE.replace("ID", "7")
                + r#"
                    const steps = fog.pulse({ min: 0.2, max: 1.0, periodMs: 1500 });
                    if (steps.length !== 1) throw new Error("expected 1 step, got " + steps.length);
                    const s = steps[0];
                    if (s.id !== 7) throw new Error("expected id == 7");
                    if (s.primitive !== "setFogAnimation")
                        throw new Error("expected primitive == setFogAnimation, got " + s.primitive);
                    if (s.args === null) throw new Error("expected args !== null");
                    if (s.args.periodMs !== 1500) throw new Error("expected periodMs == 1500");
                    if (s.args.phase !== null) throw new Error("expected phase === null");
                    if (s.args.playCount !== null) throw new Error("expected playCount === null (loop forever)");
                    JSON.stringify(s.args.density)
                "#;
            let json: String = ctx.eval(src).unwrap();
            let densities: Vec<f64> = serde_json::from_str(&json).unwrap();
            assert_eq!(densities.len(), 17);
            let lo = 0.2_f64;
            let hi = 1.0_f64;
            let mid = (lo + hi) * 0.5;
            let amp = (hi - lo) * 0.5;
            for (i, &got) in densities.iter().enumerate() {
                let theta = (i as f64 / 16.0) * std::f64::consts::PI * 2.0;
                let expected = mid + amp * theta.sin();
                assert!(
                    (got - expected).abs() < 1e-5,
                    "sample {i}: expected {expected}, got {got}"
                );
            }
            // Wrap sample: sample[16] must equal sample[0].
            assert!(
                (densities[16] - densities[0]).abs() < 1e-5,
                "wrap sample[16] must equal sample[0]; got {} vs {}",
                densities[16],
                densities[0]
            );
        });
    }

    #[test]
    fn fog_handle_fade_returns_single_step_one_shot_set_fog_animation() {
        // `fog.fade({ ... })` must emit exactly one `setFogAnimation` step
        // whose `args.density` is a 16-sample linear ramp from `from` to
        // `to`, with `playCount = 1` (one-shot). See
        // `fog_handle_pulse_...` for the shape rationale.
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let src = FOG_HANDLE_FIXTURE.replace("ID", "11")
                + r#"
                    const steps = fog.fade({ from: 0.0, to: 4.0, periodMs: 750 });
                    if (steps.length !== 1) throw new Error("expected 1 step, got " + steps.length);
                    const s = steps[0];
                    if (s.id !== 11) throw new Error("expected id == 11");
                    if (s.primitive !== "setFogAnimation")
                        throw new Error("expected primitive == setFogAnimation, got " + s.primitive);
                    if (s.args === null) throw new Error("expected args !== null");
                    if (s.args.periodMs !== 750) throw new Error("expected periodMs == 750");
                    if (s.args.phase !== null) throw new Error("expected phase === null");
                    if (s.args.playCount !== 1) throw new Error("expected playCount === 1 (one-shot)");
                    JSON.stringify(s.args.density)
                "#;
            let json: String = ctx.eval(src).unwrap();
            let densities: Vec<f64> = serde_json::from_str(&json).unwrap();
            assert_eq!(densities.len(), 16);
            let from = 0.0_f64;
            let to = 4.0_f64;
            for (i, &got) in densities.iter().enumerate() {
                let t = i as f64 / 15.0;
                let expected = from + (to - from) * t;
                assert!(
                    (got - expected).abs() < 1e-5,
                    "sample {i}: expected {expected}, got {got}"
                );
            }
            assert!((densities[0] - from).abs() < 1e-6);
            assert!((densities[15] - to).abs() < 1e-6);
        });
    }

    #[test]
    fn sdk_prelude_installs_globals() {
        // The prelude rewrites `export const world = ...` and friends as
        // `globalThis.x = ...` assignments. After the capability-handle
        // refactor, `flicker` / `pulse` / `colorShift` / `sweep` /
        // `fogPulse` / `fogFade` are no longer exported from `index.ts` —
        // they live as methods on `LightEntityHandle` / `FogVolumeHandle`.
        // Verify the still-global surface (`world`, `timeline`, `sequence`)
        // and that the dropped names are absent.
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let typeof_world: String = ctx.eval("typeof world").unwrap();
            assert_eq!(typeof_world, "object", "world missing");
            for fn_name in ["timeline", "sequence", "getGameState", "defineTheme"] {
                let kind: String = ctx
                    .eval(format!("typeof {fn_name}").as_str())
                    .unwrap_or_else(|e| panic!("{fn_name}: {e}"));
                assert_eq!(kind, "function", "{fn_name}");
            }
            for absent in [
                "flicker",
                "pulse",
                "colorShift",
                "sweep",
                "fogPulse",
                "fogFade",
            ] {
                let kind: String = ctx
                    .eval(format!("typeof {absent}").as_str())
                    .unwrap_or_else(|e| panic!("{absent}: {e}"));
                assert_eq!(
                    kind, "undefined",
                    "{absent} must NOT be a bare global after the capability-handle refactor"
                );
            }
        });
    }

    #[test]
    fn define_theme_returns_token_strings_without_enumerating_helpers() {
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let result: String = ctx
                .eval(
                    r#"
                    const theme = defineTheme({
                      colors: { "hud.text": [1, 1, 1, 1] },
                      fonts: { "hud.status": "JetBrains Mono" },
                      spacing: { "hud.gap": 8 },
                    });
                    theme.colors["late.color"] = [0, 1, 0, 1];
                    delete theme.colors["hud.text"];
                    const text = Text({
                      content: "empty token",
                      color: theme.tokens.color(""),
                      font: theme.tokens.font(""),
                    });
                    const stack = VStack({
                      gap: theme.tokens.spacing(""),
                      padding: theme.tokens.spacing(""),
                    }, [text]);
                    JSON.stringify({
                      color: theme.tokens.color("hud.text"),
                      font: theme.tokens.font("hud.status"),
                      spacing: theme.tokens.spacing("hud.gap"),
                      unknown: theme.tokens.color("late.color"),
                      empty: theme.tokens.spacing(""),
                      invalid: theme.tokens.font(42),
                      textColor: text.color,
                      textFont: text.font,
                      stackGap: stack.gap,
                      stackPadding: stack.padding,
                      keys: Object.keys(theme),
                      assigned: Object.keys(Object.assign({}, theme)),
                      json: JSON.stringify(theme),
                    })
                    "#,
                )
                .unwrap();
            let got: serde_json::Value = serde_json::from_str(&result).unwrap();
            assert_eq!(got["color"], "hud.text");
            assert_eq!(got["font"], "hud.status");
            assert_eq!(got["spacing"], "hud.gap");
            assert_eq!(got["unknown"], "late.color");
            assert_eq!(got["empty"], "");
            assert_eq!(got["invalid"], "42");
            assert_eq!(got["textColor"], "");
            assert_eq!(got["textFont"], "");
            assert_eq!(got["stackGap"], "");
            assert_eq!(got["stackPadding"], "");
            assert_eq!(
                got["keys"],
                serde_json::json!(["colors", "fonts", "spacing"])
            );
            assert_eq!(
                got["assigned"],
                serde_json::json!(["colors", "fonts", "spacing"])
            );
            assert!(
                !got["json"].as_str().unwrap().contains("tokens"),
                "defineTheme helper metadata must not enter JSON theme data"
            );
        });
    }

    #[test]
    fn get_game_state_returns_same_frozen_hidden_reference_tree() {
        let (subsys, _ctx) = setup();
        subsys.definition_ctx().with(|ctx| {
            let result: String = ctx
                .eval(
                    r#"
                    const first = getGameState();
                    const second = getGameState();
                    if (first !== second) throw new Error("getGameState must return the captured singleton");
                    if (typeof globalThis.__postretroGameStateRefs !== "undefined")
                        throw new Error("bridge global leaked");
                    if (first.player.health.slot !== "player.health")
                        throw new Error("bad player.health slot: " + first.player.health.slot);
                    if (first.player.maxHealth.slot !== "player.maxHealth")
                        throw new Error("bad player.maxHealth slot: " + first.player.maxHealth.slot);
                    if ("ammo" in first.player)
                        throw new Error("removed player.ammo path is still exposed");
                    if (!Object.isFrozen(first) || !Object.isFrozen(first.player) || !Object.isFrozen(first.player.health))
                        throw new Error("state tree must be deeply frozen");
                    try { first.player.health.slot = "mutated"; } catch (_) {}
                    try { first.player = {}; } catch (_) {}
                    if (first.player.health.slot !== "player.health")
                        throw new Error("leaf mutation changed slot");
                    if (first.player.health !== second.player.health)
                        throw new Error("leaf identity changed across calls");
                    JSON.stringify({ health: first.player.health, maxHealth: first.player.maxHealth })
                    "#,
                )
                .unwrap();
            assert_eq!(
                result,
                r#"{"health":{"slot":"player.health"},"maxHealth":{"slot":"player.maxHealth"}}"#
            );
        });
    }
}
