[package]
name = "postretro-level-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Level compiler for Postretro"
license.workspace = true

[[bin]]
name = "prl-build"
path = "src/main.rs"

[dependencies]
postretro-level-format = { workspace = true, features = ["serde", "gltf-resolve"] }
shambler.workspace = true
glam.workspace = true
anyhow.workspace = true
log.workspace = true
env_filter = "1"
thiserror.workspace = true
rayon.workspace = true
bvh = { version = "0.11", default-features = false }
nalgebra = { version = "0.33", default-features = false, features = ["std"] }
png.workspace = true
image.workspace = true
blake3 = "1"
bytemuck = { workspace = true }
postcard = { version = "1", features = ["alloc"] }
serde.workspace = true
serde_json.workspace = true
ratatui = { version = "0.28", default-features = false, features = ["crossterm", "unstable-rendered-line-info"] }
crossterm = "0.28"

[dev-dependencies]
proptest = { workspace = true }
